### ISSUE TITLE
STATUS QUESTION | continuing active development on Sidebery?

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#484] opened 2021-10-01 14:35 UTC
Many users are interested in using sidebery as a primary tool in their daily workflows. It is exceptionally well-designed and engineered for significant augmentation of Firefox.

Huge thanks to Max @mbnuqw and the other contributors - @ongots, Alexandria @akvail and Ricky @rigrassm for their _literally_ world-changing work on this project. The productivity increases and workflow enhancements made possible by a tool like sidebery create enormous advantages for users on a daily basis. 

However, for the tool to continue to be used, it must be basically reliable. There are a number of fundamental bugs that make sidebery unusable for practical purposes at this time. Particularly, tab group hierarchy is completely destroyed on Firefox restart; and group creation and management features behave quite strangely in Firefox 92+. These issues (and others) have been reported by numerous users. It appears that developer involvement in issue discussions tapered off in June 2021 and many tickets remain unaddressed since then.

To help users consider whether to work with this tool and continue spending time reporting issues: 
Is active development continuing on sidebery? There was a version 5.0 mentioned previously; is this still in the works?

Also, please do advise us users if you are needing a donation/sponsorship boost or other support at this time. We really do benefit greatly from (and frankly, need a tool like) sidebery, and many of us would contribute in one way or another if we knew exactly what was needed at this time to keep development going.

Thanks again, and please let us know!

**Comment by pintassilgo** [comment] 2021-10-01 15:16
> Particularly, tab group hierarchy is completely destroyed on Firefox restart

I can't reproduce such issue. I'm new to Sidebery (2 weeks), but as for now it has been reliable (and I come from Tree Styla Tab that was never able to be reliable when switching groups). It may be relevant to say that I use "session storage" instead of default "global storage" because, as said in settings, session storage is more accurate.

---

From the complains I have so far, most are more like feature requests than *bugs*. I have been fixing some things in [my fork](https://github.com/pintassilgo/sidebery/commits/master), but always focusing on my needs instead of doing exhaustive tests with settings different from mine.

**Comment by boldcompany** [comment] 2021-10-01 15:39
> 
> 
> > Particularly, tab group hierarchy is completely destroyed on Firefox restart
> 
> I can't reproduce such issue. I'm new to Sidebery (2 weeks), but as for now it has been reliable (and I come from Tree Styla Tab that was never able to be reliable when switching groups). It may be relevant to say that I use "session storage" instead of default "global storage" because, as said in settings, session storage is more accurate.
> 

Thanks, @pintassilgo . In a brand-new default instance of Firefox 92.0.1 with Sidebery 4.9.4, and testing alternatively with both session storage and global storage options, the strange issues occur with 100% repeatability. Would it be helpful to have a screensharing session so you can review?

Issue tickets such as #442, #482, #341, #319, #267, #262 and #371 are representative of these issues and remain open. If a user cannot rely on sidebery to maintain basic panel/group structure, then it really is not usable.

In issue ticket #386, Max @mbnuqw mentions that there are issues with internal tabs ordering, which would hopefully be fixed in v5. Do you know if such a release is still planned and if development is ongoing?

**Comment by pintassilgo** [comment] 2021-10-02 01:13
Unfortunately I couldn't reproduce any of these issues, which are maybe multiple reports of the same bug. Tested in a new profile with default settings. Tried to import settings from some of the reports, under "Details", also without success.

Unless someone provides consistent steps to reproduce, it's hard to debug what's causing the issue. It may be related to some external factors like Firefox Sync and conflicts with other addons. That's probably why it wasn't fixed yet, you can see the dev saying he couldn't reproduce the issue.

A possibility to try to trace down the issue:
1. Clone the entire Firefox profile to avoid damaging anything in your default profile.
2. Make multiple tests disabling other extensions one by one, resetting Sidebery settings, disabling Firefox Sync, even deleting prefs.js to restart Firefox settings (without removing Sidebery)... Until find the culprit.

**Comment by boldcompany** [comment] 2021-10-02 02:54
> Unfortunately I couldn't reproduce any of these issues, which are maybe multiple reports of the same bug. Tested in a new profile with default settings. Tried to import settings from some of the reports, under "Details", also without success.

Well, it seems very interesting that in your environment, you are not seeing the issues, but others are in their environments. Here is a basic set of steps to reproduce the issues:

1. Install a fresh instance of Firefox 92.0.1 on a Windows 10 machine.
2. Install the sidebery 4.9.4 add-on.
3. Create a few panels. Open 20-30 tabs in those panels.
4. Create groups within the panels and organize the tabs into the groups.

Without more effort than this, you can see the strange group-management behaviors and collapsing panel/group hierarchies as noted in the previously-mentioned tickets.

**Comment by pintassilgo** [comment] 2021-10-02 04:02
Did exactly as you said, having 3 panels with 20 tabs on each, with 2 or 3 groups within each panel with some tabs in them.

Default Sidebery 4.9.4. The only change in Firefox settings was to enable session restore.

Restarted a few times, everything is workings as expected.

**Comment by strogonoff** [comment] 2021-10-04 14:48
I hadn't had many issues with sidebery; I did lose tabs or tab hierarchy (can't remember) but only once, and I restarted Firefox dozens of times.

**Comment by OJFord** [comment] 2022-02-19 18:37
FYI I just noticed there was a v5 beta release 25 days ago, and the latest one just 2 days ago. 🎉 I look forward to trying it out/helping test.

I probably can't also throw my hat in the ring as far as contributions go (limited JS, no FF add-on experience) but I can test-drive the beta, and maybe help with issue triage if that's of any use to you @mbnuqw.

**Comment by mxmilkiib** [comment] 2023-07-20 13:09
I'm ctrl-f-ing the Sidebery settings page for "global" "session" and "storage" but I can't see the relavent setting. I guess something has changed? I moved to Sidebery a couple of weeks ago after TST, but the panel resetting and tree flattening thing are a big pain point. Thanks for any advice. Edit: [config](https://gist.github.com/mxmilkiib/06832f9ae80ed853de09ebc7cf842c45), fwiw

**Comment by KRACK-BIT** [comment] 2023-07-20 17:35
> Particularly, tab group hierarchy is completely destroyed on Firefox restart

For what it counts, I have had the same phenomena plague me for most of the 2-3 years that I have been using it, and found it significantly hampering my Sidebery experience.

However (and to be clear, this might just be for me), I found that I no longer had this issue so long as I made sure that Sidebery was not taking a snapshot whilst I'm quitting firefox.

(Also disclaimer; it's common for me to have 2000+ tabs open, so snapshots for me cause a visible lag spike and made it's v obvious when they coincided)

---

Lastly, on the purpose of this issue; since it seems like most current devs are working on 5.0, does anyone know what the roadmap for this project might be? Would be good not only to know how far Sidebery is from its next release, but also in letting new devs know what they could do to contribute.

**Comment by albino1** [comment] 2023-07-20 17:46
If you're having this issue you're probably still on v4.  You need to switch to v5:

https://github.com/mbnuqw/sidebery/releases

**Comment by mxmilkiib** [comment] 2023-07-20 20:33
@albino1 A-ha, thanks! I just installed it though the regular extensions system, where I realise now it is verison 4.10.2 (28 Aug 2022)

**Comment by mbnuqw** [comment] 2024-03-17 13:21
Some info about current status and stuff.

I'm still continuing development on this project. I'm not planning to sell it or to use shady methods of monetization. For me, it's still a project for productivity/usability boost and ux experiments, that I use myself.

I can't promise ongoing support 24/7. I also can't promise support on feature requests that don't interest me or bugs that don't annoy me. There also might be pauses of activity on this project. If you want some feature to get implemented or bug fixed, you have the next options:
- Wait if the issue is marked as planned (or it appeared in milestone, or I assigned myself to it)
- Implement it yourself and create PR, although I can't guarantee that it will be merged
- Email me the issue link you're interested in, we'll discuss if it's possible to implement/fix it, donate (right now crypto options only) and I'll spend my time on it.

My current todo for this project:
- Deal with unlabeled issues
- Classify/label issues, add new issues from my local task list
- Fill the v5.3.0 milestone and slowly continue development

**Closed by mbnuqw** 2024-03-17 13:21 UTC
