### ISSUE TITLE
The possibility to give pinned tabs a fixed title

### ISSUE THREAD

**Issue by mbrasch** [mbnuqw/sidebery#628] opened 2022-05-04 18:39 UTC
## Description
It would be helpful if pinned tabs could be given a fixed title. I very often have the problem that pages are only accessible in the intranet and the titles are then not meaningful when hovering.

In many cases, you are also redirected via an SSO page, which also changes the tab title so that you can no longer find the tab. I have 3 rows of pinned tabs here for my work.

I hope there is a nice way to implement this.

-- 
Best Regards
Mike

**Comment by mbnuqw** [comment] 2022-05-09 13:40
Duplicate of #185
This feature is still planned (but with low priority)

Feel free to reopen if this is not a duplicate.

**Closed by mbnuqw** 2022-05-09 13:40 UTC
