### ISSUE TITLE
More symbols for panels

### ISSUE THREAD

**Issue by dwian** [mbnuqw/sidebery#1418] opened 2024-01-17 11:20 UTC
Instead of using svg for the symbols representing the panels you could use the (free) characters of fontawesome. Colorselection would be as easy as now and there are lot more symbols to choose from.
Instead of desaturating the symbol when disabled, I would prfer inverting front- and backcolor.

**Comment by mbnuqw** [comment] 2024-03-30 12:18
Duplicate of #1025
Related: #1393

**Closed as completed by mbnuqw** 2024-03-30 12:18 UTC
Labels: type: duplicate
