### ISSUE TITLE
Compatibility with Adaptive Tab Bar Color and multiple windows 

### ISSUE THREAD

**Issue by infinatious** [mbnuqw/sidebery#1460] opened 2024-02-12 17:27 UTC
## Description
When using this extension with the extension Adaptive Tab Bar Color (changes window color depending on the active tab), the color of the sidebar changes for both windows depending on which one is active. Desired functionality would be that both windows color are independent depending on the tab in that window and match the Firefox header of that window regardless of which window is active.

**Comment by emvaized** [comment] 2024-02-14 22:41
Possibly a duplicate of https://github.com/mbnuqw/sidebery/issues/1134? 

However, this issue was already fixed [here](https://github.com/mbnuqw/sidebery/commit/d8790dc1129e4c2bebaa2b258ceabd2bb5fa2221). Are you sure you're using the latest version of Sidebery (v5)?

**Comment by infinatious** [comment] 2024-02-14 22:55
I am still experiencing this issue on 5.1.1. I see the fix was implemented recently so maybe I just need to wait for the next update.

**Comment by SunnyZebra** [comment] 2024-03-07 13:59
In previous stable 5.1.1 version fix was not yet worked on. Was only added inside the nightly afterwards.

Adaptive Tab Bar Color compatibility working for me in recently released version 5.2.0.1.

**Comment by mbnuqw** [comment] 2024-03-08 05:41
Fixed from v5.2.0

**Closed as completed by mbnuqw** 2024-03-08 05:41 UTC
Labels: type: duplicate
