### ISSUE TITLE
After close parent tab don't flat the tree

### ISSUE THREAD

**Issue by Dimas-sc** [mbnuqw/sidebery#255] opened 2020-05-28 07:32 UTC
Steps to reproduce:
- I've an open tree
- Close the parent tab

What happens? The tree is lost, all the child tabs are don't have parent tab.
What I'd like? The next child tab should be the parent tab and the other ones should continue to be child tabs of it.

Is there any option for this behavior?
Thx

**Comment by mbnuqw** [comment] 2020-05-28 16:49
Duplicate of #140

**Closed by mbnuqw** 2020-05-28 16:49 UTC
