### ISSUE TITLE
New tab in panel don't open in container

### ISSUE THREAD

**Issue by berliozz** [mbnuqw/sidebery#305] opened 2020-09-07 06:25 UTC
## Steps to reproduce
1. Open Settings → Panel → Click to any panel
2. Set container for new tab
3. Close settings
4. Switch to panel
5. Create new tab
6. Tab open in default container

## Expected behavior
Tab must be opened in container pointed in p.2 of step to reproduce

## Actual behavior
Tab open in default container

## Environment info

OS:  macos ﻿﻿10.15.6
Firefox version:  80.0.1 (64Bit)
Addon version:  4.9.0

Installed additional addon: Firefox Multi-Account Containers (7.0.2)

<details><code>
<!-- To get details: 
     - Go to the settings page - section "Help"
     - Click on the "Debug info" button
     - Copy and paste here, inside the <code>Firefox Multi-Account Containers

General
Context menu
Use comma-separated list of contaianers names or /regexp/
Navigation bar
Group page
Containers
Panels
Drag and Drop
Tabs
- global storage - fast, but inaccurate in rare cases.
- session storage - more strict, but slower. (Warning: Tabs data will be removed along with Browser Session)
  Note: If you have issues with incorrectly restored tabs, try to reopen sidebar and change this option.
Position of new tab
Pinned tabs
Tabs tree
Bookmarks
Appearance
Notes:
- To apply theme color to Sidebery buttons in browser interface set "svg.context-properties.content.enabled" to "true" in about:config page.
Mouse
Keybindings
Open/Close sidebar panel
Ctrl+E
off
on
Switch to next panel
Alt+Period
off
on
Switch to previous panel
Alt+Comma
off
on
Open new tab in active panel
Ctrl+Space
off
on
Open new tab after active tab
Ctrl+Shift+Space
off
on
Open new tab as the first child of active tab
---
off
on
Open new tab as the last child of active tab
---
off
on
Remove selected items or active tab
---
off
on
Select all
---
off
on
Up
Alt+Up
off
on
Down
Alt+Down
off
on
Select up
Alt+Shift+Up
off
on
Select down
Alt+Shift+Down
off
on
Activate selection
Alt+Space
off
on
Open menu
---
off
on
Reset selection
Alt+R
off
on
Fold selected branch
---
off
on
Expand selected branch
---
off
on
Fold inactive branches
---
off
on
Active tabs history: Back
---
off
on
Active tabs history: Next
---
off
on
Active tabs history of panel: Back
---
off
on
Active tabs history of panel: Next
---
off
on
Move selected tabs to the active tab
---
off
on
Increase tab's tree level (indent)
---
off
on
Decrease tab's tree level (outdent)
---
off
on
Move tabs up
---
off
on
Move tabs down
---
off
on
Create snapshot
---
off
on
Switch to first panel
---
off
on
Switch to second panel
---
off
on
Switch to third panel
---
off
on
Switch to fourth panel
---
off
on
Switch to fifth panel
---
off
on
Switch to sixth panel
---
off
on
Switch to seventh panel
---
off
on
Switch to eighth panel
---
off
on
Switch to ninth panel
---
off
on
Switch to tenth panel
---
off
on
Permissions
Required for:
- Cleaning cookies
- Proxy and URL rules of containers
- Screenshots for the group page and windows selection panel
- Changing the User-Agent per container
Required for:
- Hiding tabs in inactive panels
- Hiding folded tabs
Required for:
- Copying URLs of tabs/bookmarks through context menu
Required for:
- Changing the User-Agent per container
Snapshots
Storage
 (~325.9 kb)
favicons
~303.5 kb
tabsData_v4
~4.9 kb
prevTabsData_v4
~4.6 kb
settings
~2.7 kb
favUrls
~2.4 kb
cssVars
~1.5 kb
panels
~1.4 kb
tabsTrees
~1.1 kb
prevTabsTrees
~869 b
panels_v4
~812 b
containers_v4
~787 b
tabsMenu
~308 b
bookmarksMenu
~226 b
tabsPanelMenu
~184 b
disabledKeybindings
~90 b
bookmarksPanelMenu
~54 b
profileID
~14 b
favAutoCleanTime
~10 b
expandedBookmarks
~2 b
panelIndex
~1 b
Sync
 (~3.5 kb)
Settings
wbO8gkDTG3hN - 2020.04.23 - 16:04:46 - 2.6 kb
Context menu
wbO8gkDTG3hN - 2020.04.23 - 16:04:45 - 911 b
Help
Note: Updating tabs may cause them to be rearranged
OS: mac
Firefox: 80.0.1
Addon: 4.9.0
{
  "settings": {
    "version": "4.9.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": true,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "none",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": 2,
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xs",
    "bgNoise": false,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "light",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "326.1 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "787 b",
      "cssVars": "1.5 kb",
      "disabledKeybindings": "90 b",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "2.4 kb",
      "favicons": "303.5 kb",
      "panelIndex": "1 b",
      "panels": "1.4 kb",
      "panels_v4": "812 b",
      "prevTabsData_v4": "4.6 kb",
      "prevTabsTrees": "869 b",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "5.1 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b",
      "tabsTrees": "1.1 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": true,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "vpxSOUXNNKQA",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-2",
      "dropTabCtx": "firefox-container-2",
      "moveTabCtx": "firefox-container-2",
      "moveTabCtxNoChild": false,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": {
    "tabs_font": "0.8rem sans-serif"
  },
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 43
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 30,
    "foldersCount": 6,
    "separatorsCount": 1,
    "maxDepth": 2
  }
}

</code></details>

**Comment by ozars** [comment] 2020-11-10 17:44
I had same issue, which is quite annoying since I had to reassign container for every new tab. I figured there is a simpler solution: using ctrl + space for new tabs instead of ctrl + t. You can rebind this to another shortcut from sideberry settings. FF doesn't allow extensions to rebind ctrl + t though.

![image](https://user-images.githubusercontent.com/13993759/98710615-853ec400-2349-11eb-94dc-c30ca5a32aa8.png)

**Comment by ShiromMakkad** [comment] 2022-07-09 04:37
Any updates on this? TreeStyle tab was able to solve this. I know you said there's no optimal solution, but an unoptimal solution that's off by default and we had the ability to turn on would be nice.

**Comment by ovnis82** [comment] 2022-10-25 15:19
Bug confirmed

**Comment by mbnuqw** [comment] 2023-09-29 12:26
Resolved (as a workaround) in v5.0.0 (Sidebery settings >> Navigation bar >> Panel config popup >> Detect externally opened tab... sub-option)

**Closed by mbnuqw** 2023-09-29 12:26 UTC
Labels: type: bug, dep: api limitation, status: resolved in beta

**Comment by Qwerty-Space** [comment] 2024-04-22 13:35
> Resolved (as a workaround) in v5.0.0 (Sidebery settings >> Navigation bar >> Panel config popup >> Detect externally opened tab... sub-option)

That doesn't seem to work for me.  I've enabled that setting, but when I press ctrl+t in that panel, it still opens with no container

**Comment by earslap** [comment] 2024-10-05 22:06
> That doesn't seem to work for me. I've enabled that setting, but when I press ctrl+t in that panel, it still opens with no container

I think that is expected with this setting. The tab opens with no container but when you make a network request (enter an address and press enter) Sideberry automatically recreates the tab with the correct container.
