### ISSUE TITLE
Unhandled URL

### ISSUE THREAD

**Issue by HenryTheVacuum** [mbnuqw/sidebery#323] opened 2020-11-14 19:10 UTC
Having issues with Unhandled URL pages showing instead of the intended tab.

The actual URL is still available in the URL bar, but about:blank is messing with it?

moz-extension://34b827b0-a2f0-4694-bbf6-76bfa9a5d09d/url/url.html#about:blank#urlhttps://www.google.com

**Comment by btglr** [comment] 2021-06-09 09:10
I have had this recurring problem too, and it's causing tabs to silently disappear when Firefox is closed and reopened. Can you look into it @mbnuqw?

**Comment by KetanBasi** [comment] 2021-07-21 12:15
![image](https://user-images.githubusercontent.com/23256673/126485738-9c1bd758-8ef6-4a97-85f8-c2a3c826a827.png)
Restoring from snapshots always gives me this problem too

**Comment by ellidi** [comment] 2022-03-21 11:51
This is still a problem :/

**Comment by 2ndemosthenes** [comment] 2022-03-25 13:42
I have this problem too, any way to solve it?

**Comment by albino1** [comment] 2022-08-29 19:22
Edit: I moved to v5, everything seems to be working fine now.

**Comment by koppor** [comment] 2023-03-20 15:53
I think, the issue reported at https://github.com/mbnuqw/sidebery/issues/323#issuecomment-1096297415 also effects the way tabs are restored when pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>. - When accidently closing a window with grouped tabs, the whole hierarchy is lost in v5 as of today.

**Comment by mbnuqw** [comment] 2024-03-10 08:15
Should be fixed in the latest version. Please, reopen if the issue is reproduced in the latest version of Sidebery.

**Closed by mbnuqw** 2024-03-10 08:15 UTC
