### ISSUE TITLE
[v5] Tabs don't load after Firefox restart

### ISSUE THREAD

**Issue by michalfita** [mbnuqw/sidebery#798] opened 2022-10-10 16:02 UTC
Tree Style Tabs work OK for me, I decided to give Sidebery a try for the search features, but I had trouble with container (another topic) and after restarting Firefox I don't see any tabs in panels. That makes the extension useless for me.

## Expected behavior
All tabs in place after restarting Firefox.

## Actual behavior
Empty panels.

## Debug info
Firefox 105.0.3 on Windows 11.

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": false,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": false,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "s",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "clipboardWrite": false,
    "webRequest": false,
    "webRequestBlocking": false
  },
  "storage": {
    "size": "76.5 kb",
    "props": {
      "containers": "969 b",
      "favDomains": "3.15 kb",
      "favHashes": "293 b",
      "favicons": "25.6 kb",
      "prevTabsDataCache": "41.9 kb",
      "profileID": "14 b",
      "settings": "3.61 kb",
      "sidebar": "826 b",
      "tabsDataCache": "2 b",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "tabs-panel": {
        "type": 2,
        "id": "tabs-panel",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": false,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "LkWYiuNJbZHb": {
        "type": 2,
        "id": "LkWYiuNJbZHb",
        "name": "len: 7",
        "color": "purple",
        "iconSVG": "icon_man",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "firefox-container-1",
        "dropTabCtx": "firefox-container-1",
        "moveTabCtx": "firefox-container-1",
        "moveTabCtxNoChild": false,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "tabs-panel",
      "LkWYiuNJbZHb",
      "search",
      "add_tp",
      "sp-0",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "purple",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 489
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 379
    }
  ],
  "bookmarks": "TypeError: browser.bookmarks is undefined"
}
</code></details>

### Logs
<details><code>

</code></details>

**Comment by megamorphg** [comment] 2022-10-10 19:22
I'm on 105.0.3 and never got this issue. All tabs in all panels are kept across restarts.

you should try to manually reproduce the issue in a test profile with only Sidebery and update "Steps to Reproduce" section

**Comment by michalfita** [comment] 2022-10-10 20:19
I can't promise I'll find time to play with this, but what's specific to my setup is that I have two windows opened. One with 300 tabs no containerized, other with similar amount all in container. These containerized tabs never appeared in any panel from the start even if I fiddled with settings.

**Comment by albino1** [comment] 2022-10-10 22:01
~~They don't restore for me either using v5.  There's a thread about this here:~~

https://github.com/mbnuqw/sidebery/issues/721

In the meantime, take advantage of the Snapshots feature and just start making snapshots before you close Firefox.  I have auto-Snapshots being created on a schedule, but I also pinned the Create Snapshot icon to the Navigation Bar in Sidebery so I can just quickly hit it whenever I go to close the browser:

![snapshot pinned](https://user-images.githubusercontent.com/12164957/194958797-579e2e05-d4ce-4b18-8e3c-75292e9bbd74.jpg)

Edit: Appears to be working now after an uninstall/re-install of v5.

**Comment by megamorphg** [comment] 2022-10-10 23:10
> One with 300 tabs no containerized, other with similar amount all in container. These containerized tabs never appeared in any panel from the start even if I fiddled with settings.

I have about a dozen containerized tabs in 4 different containers in different windows and they all exist after every restart and load fine.

I think this has something to do with **panels in combination with containers** because I don't use panels at all and do not have any issues with missing tabs on latest beta.

**Comment by danielnichols** [comment] 2022-10-10 23:24
I have had issues with this as well, although I can't say if it's the exact same issue. I have about 2,000 tabs open across about 30 windows, and I find that when I restart Firefox, the first few windows don't show anything in the Sidebery sidebar, even though the tabs do exist.

My workaround is to close and reopen the Sidebery sidebar in those windows, and then the tabs will show up. You can make this quicker to do by adding a keybinding to open the Sidebery sidebar.

Also for the record, I also use multiple panels and containers, but it seems that this issue is unrelated at least for me, as it still shows up with a single panel only and no containers. I'd say that this issue has more to do with the number of tabs or windows, and how that affects Firefox's startup time. Perhaps a race condition?

**Comment by albino1** [comment] 2022-10-10 23:44
So I've just done a fresh uninstall and re-install of Sidebery v5 and it appears to be working now, so maybe try that.

Also, make sure that `Open previous windows and tabs` is checked in `about:preferences`.

**Comment by megamorphg** [comment] 2022-10-11 00:56
> I have had issues with this as well, although I can't say if it's the exact same issue. I have about 2,000 tabs open across about 30 windows, and I find that when I restart Firefox, the first few windows don't show anything in the Sidebery sidebar, even though the tabs do exist.

@danielnichols I had this issue too and also have about 2k tabs across 10 windows (and also had an issue where the window prefix created via Window Titler Add-On would go away and come back changing between tabs during the initial load).

The fix is as you say but the solution may be to not interrupt the initial loading process. I give Firefox about a minute to "settle" and don't even touch the mouse. Also recently relocated Firefox to a faster M2 and am on the latest 105.0.3 (compared to when I previously noticed)... so it could be one of those factors.

**Comment by mbnuqw** [comment] 2023-01-26 18:35
Should be fixed in v5.0.0b30. Please reopen if the issue is still present.

**Closed as completed by mbnuqw** 2023-01-26 18:35 UTC
Labels: type: bug, reproduced: yes
