### ISSUE TITLE
List and manage tabs across different Windows 

### ISSUE THREAD

**Issue by Malaccoda** [mbnuqw/sidebery#1321] opened 2023-10-14 17:17 UTC
## Description
I have a multi display setup and usually there is on each display at least one (or more) firefox window running. I thought about something like a button "show all tabs / only tabs in this window" and in the context menu a shortcut to which window the tab should be assigned.

**Comment by mbnuqw** [comment] 2024-03-28 11:09
Duplicate of #137

**Closed as completed by mbnuqw** 2024-03-28 11:09 UTC
Labels: type: duplicate
