### ISSUE TITLE
Dynamic native tabs CSS it's not working

### ISSUE THREAD

**Issue by GamaG27** [mbnuqw/sidebery#1089] opened 2023-06-30 20:07 UTC
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Enable toolkit.legacyUserProfileCustomizations.stylesheets in about:config
- Create folder chrome with file userChrome.css
- Edit CSS with snippet (https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs)

In the console of DevTools toolbox of the extension nothing appears but in the toolbox of the browser a lot of errors appear, I can't recognize if any have to do with this though

## Expected behavior
Hide native Firefox tab bar when pressing F1 (opens Sidebery shortcut)

## Actual behavior
The native Firefox tab bar slightly moves

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
{
  "settings": {
    "version": "4.10.2",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": true,
    "markWindowPreface": "XXX",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "prev_act",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 3,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "first_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "top",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": 2,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": true,
    "discardFoldedDelay": 5,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "xs",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "exp",
    "tabLongLeftClick": "clear_cookies",
    "tabLongRightClick": "new_child",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "undo",
    "syncName": "Firefox Dev",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "290.7 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "2 b",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "3.2 kb",
      "favicons": "282.4 kb",
      "panelIndex": "1 b",
      "panels_v4": "446 b",
      "prevTabsData_v4": "187 b",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "sidebarCSS": "2 b",
      "tabsData_v4": "623 b",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "sidebarCSSLen": 0,
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 5
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 1116,
    "foldersCount": 40,
    "separatorsCount": 0,
    "maxDepth": 4
  }
}
```
</details>

<details>
<summary><b>Logs</b></summary>

```
To get logs: 
- Open DevTools (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension).
- Navigate to "console" tab.
- Click on the trash bin icon (at the top-left) to clear console.
- Then try to reproduce the issue.
- If messages appear, copy and paste them here inside this codeblock, replacing this text.
```

</details>

**Comment by chinook77** [comment] 2023-07-20 20:41
> ## Steps to reproduce
> 
>     * Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
> 
>     * Install Sidebery
> 
>     * Enable toolkit.legacyUserProfileCustomizations.stylesheets in about:config
> 
>     * Create folder chrome with file userChrome.css
> 
>     * Edit CSS with snippet (https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs)
> 
> 
> In the console of DevTools toolbox of the extension nothing appears but in the toolbox of the browser a lot of errors appear, I can't recognize if any have to do with this though
> ## Expected behavior
> 
> Hide native Firefox tab bar when pressing F1 (opens Sidebery shortcut)
> ## Actual behavior
> 
> The native Firefox tab bar slightly moves
> ## Debug info
> Addon data
> Logs

I have the same issue.

**Comment by mvlipka** [comment] 2023-08-02 20:44
Fixed the issue for myself.

Navigate to [about:config](about:config) and search for `browser.tabs.inTitlebar`

Set to `0`

**Comment by MahouShoujoMivutilde** [comment] 2023-09-27 19:40
Alternatively, use

```css
:root[tabsintitlebar] {
  --uc-toolbar-height: 40px;
}
:root[tabsintitlebar][uidensity='compact'] {
  --uc-toolbar-height: 32px;
}


/* works with https://unicode-explorer.com/c/200B too */
#main-window[titlepreface*='XXX'] #TabsToolbar {
  visibility: collapse !important;
}
#main-window #TabsToolbar {
  visibility: visible !important;
}

```

(Inspired by https://mrotherguy.github.io/firefox-csshacks/?file=hide_tabs_toolbar.css)

**Might need https://mrotherguy.github.io/firefox-csshacks/?file=window_control_placeholder_support.css**, not tested, since I use linux with a window manager where windows aren't _supposed to_ have controls to begin with.

**Comment by mbnuqw** [comment] 2024-03-25 12:11
Should be fixed in current wiki, at least I can't reproduce.

**Closed as completed by mbnuqw** 2024-03-25 12:11 UTC
Labels: type: bug, reproduced: no

**Comment by tlgnkl** [comment] 2024-04-09 11:53
![CleanShot 2024-04-09 at 14 52 05@2x](https://github.com/mbnuqw/sidebery/assets/67519432/74a0437f-4293-4964-8d8e-58efebc41ab6)
It's quite strange, but it's reproducing for me. Only 1/3 of the height of the tabs are hidden... It's very strange.

**Comment by tlgnkl** [comment] 2024-04-09 17:47
@mbnuqw

**Comment by mbnuqw** [comment] 2024-04-10 07:12
@OstriySous, it's probably something OS specific. Check the window control buttons. Sorry, can't help.
