### ISSUE TITLE
Consider browser.sessionstore.restore_pinned_tabs_on_demand

### ISSUE THREAD

**Issue by ongots** [mbnuqw/sidebery#603] opened 2022-04-12 14:33 UTC
With option enabled `browser.sessionstore.restore_pinned_tabs_on_demand` after restarting the browser, unloaded pinned tabs should not glow.

**Comment by mbnuqw** [comment] 2022-04-13 14:35
It's the firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1703072.
Duplicate of #380

**Closed by mbnuqw** 2022-04-13 14:35 UTC
Labels: type: duplicate
