### ISSUE TITLE
Add Keyboard Shortcuts for Opening New Tabs with Specific Profiles

### ISSUE THREAD

**Issue by FrostytheDopeman** [mbnuqw/sidebery#1187] opened 2023-08-22 20:15 UTC
Ctrl+T response on browsers defaults to tab opening with no profile. Add control for which profile is opened, or even better add the ability to slave keyboard shortcuts to open specific tabs.

**Comment by mbnuqw** [comment] 2023-08-31 10:28
Did you mean opening a tab in container? If so, it's a duplicate of https://github.com/mbnuqw/sidebery/issues/177.
If you meant Firefox Profiles - it's out of the scope of sidebery and a 'wontfix'.

**Closed as completed by mbnuqw** 2023-08-31 10:28 UTC
Labels: type: duplicate
