### ISSUE TITLE
[Feature request] Context menu item "Close branch"

### ISSUE THREAD

**Issue by token0** [mbnuqw/sidebery#623] opened 2022-05-03 04:21 UTC
## Description
To close parent and children tabs

**Comment by dexeonify** [comment] 2022-05-03 11:10
Not sure if this is worth adding a context menu entry. You can already do that in the same number of clicks by right-clicking the pointer arrow (beside the parent tab), and click "Close".

Dupe of #436

**Comment by mbnuqw** [comment] 2022-05-09 15:44
Or just right click on the parent's close button. But I'll add this option for context menu (as opt-in in the menu editor)

**Closed by mbnuqw** 2022-05-09 15:44 UTC
