### ISSUE TITLE
Sorting tabs in a group and/or a panel

### ISSUE THREAD

**Issue by y-haidar** [mbnuqw/sidebery#905] opened 2023-01-17 22:48 UTC
## Description
Sorting tabs that are in a group and/or panel by their title, URL, or last access. I tried to use `Sort tabs advanced` plugin but it sorts everything including the group tab along with panels and flatten everything.

**Comment by mbnuqw** [comment] 2023-01-20 19:00
Duplicate of #643

**Closed as completed by mbnuqw** 2023-01-20 19:00 UTC
Labels: type: duplicate
