### ISSUE TITLE
[v5] Restoring tab indentation/group and panel from sessionstore possible?

### ISSUE THREAD

**Issue by Illiou** [mbnuqw/sidebery#877] opened 2022-12-05 17:43 UTC
So after moving from Simple Tab Groups to Sidebery a few days ago, I've now also had the bug where tab indentation/grouping as well as to which panel the tabs belong is lost. I simply started Firefox normally, one window, shitton of tabs (~4700), and Sidebery sidebar shows no tabs and all panels as empty. Reloaded Sidebery and all tabs are now in the first panel.

Now I really really do hope you will be able to fix this issue soon, because as long as there is the possibility of data loss, I will very sadly have to switch back to Simple Tab Groups. :(

The thing is, the snapshot feature doesn't really help me with this kind of issue because restoring a snapshot will open an entirely new window and tabs, which means all information associated with the tabs is lost - i.e. mainly the history within the tab, but also entered data etc. And this is a no go for me. Not to mention the fact that it would probably take dozens of minutes to do with the amount of tabs.

Which brings me to my question: I saw that you store the necessary tab information in the sessionstore as well, so would it be possible to restore the information from there in case of a problem, either manually or automatically?

Thank you

**Comment by mbnuqw** [comment] 2023-01-19 15:40
Duplicate of #861. (I still can't reproduce that bug, but I tried with relatively low count of tabs (~100), so I'll continue testing).

Answering the question about restoring from sessionstore: Yes, manual restoring on failed init (automatic restoring) is planned (from cache/sessiondata and recent snapshots).

**Closed as completed by mbnuqw** 2023-01-19 15:40 UTC
Labels: type: duplicate

**Comment by Illiou** [comment] 2023-01-19 19:47
I had actually managed to force Sidebery to use the addon data embedded into the sessionstore file. I believe I hid the sidebar, deleted _tabsDataCache_ and _prevTabsDataCache_ in the addon settings, immediately quit Firefox, replaced the sessionstore file with one of the backups, started Firefox and activated the sidebar. Or maybe in a slightly different order. But then it had restored everything from the sessionstore file like nothing had happened. If you can implement a reliable automatic restore mechanism like that, would of course be great.

Also if sensible maybe you could make a debug setting or build for people facing #861 which could help you to identify the bug.
