### ISSUE TITLE
Allow user to indefinitely save a snapshot

### ISSUE THREAD

**Issue by Keagel** [mbnuqw/sidebery#239] opened 2020-05-12 15:36 UTC
## Description

Right now, snapshots are circular backups meaning when you reach the limit you set, older ones get deleted. I suggest:

- Adding the possibility to indefinitely save a chosen snapshot - for example through a button when viewing the details of a snapshot - so you can have months old snapshots even if you set the snapshot limit to a few days
- Maybe excluding user-created snapshots from the circular backup, so they wouldn't get deleted automatically (if this isn't already how it works)

**Comment by mbnuqw** [comment] 2020-05-23 20:14
Duplicate of #161

**Closed by mbnuqw** 2020-05-23 20:14 UTC
