### ISSUE TITLE
Closing multiple tabs in a row - mouse must be currently moved by a few pixels to show Close button on a next tab

### ISSUE THREAD

**Issue by tkafka** [mbnuqw/sidebery#18] opened 2019-03-27 14:12 UTC
When I want to close multiple tabs in a row, I'd love to hold mouse in place and click multiple times. What happens now is that I mouse over the close button, and click. This will close the current tab, and the next tab will appear under the mouse. However, the mouse hasn't moved, so the close button is hidden - and I can't click it.

Ideas: 

- somehow detect this situation and manually show the close button?
- or, just make the right side of the tab (same area as close button) aways close the tab - the only way user would click here is if he was already meaning to close it, only the close button didn't appear for some reason (like, not detecting the hover). I quite like this :).

**Comment by mbaz** [comment] 2019-03-27 14:19
I can't reproduce this -- I just tried it and I do get the close button without moving the mouse. Firefox 66 and Sideberry 2.2.1.

**Comment by mbnuqw** [comment] 2019-03-27 14:30
I can reproduce this and will fix it.

**Comment by mbnuqw** [comment] 2019-03-28 15:28
Fixed in v2.2.2

**Closed by mbnuqw** 2019-03-28 15:28 UTC
