### ISSUE TITLE
how to move a single nested tab

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#1430] opened 2024-01-25 23:02 UTC
## Description
Case:
A hierarchy of tabs exists in Sidebery, with perhaps 60 tabs at various nested levels underneath a top-level tab.
The user wants to move a single tab "Beans", which is at the third level of nesting and has additional nested tabs beneath it.

Current Behavior:
If the user clicks the Beans tab and drags it, all sub-nested tabs will move with it.
Unless it has been missed, there seems to be no workaround except to flatten all relevant tabs before trying to move the desired tab, but of course that destroys the desired hierarchy.

Desired Behavior:
The user would like a way to "pluck" the Beans tab from the hierarchy. Perhaps with a modifier key, clicking the tab would move only that tab; subnested tabs would move up 1 level; and the rest of the tabs hierarchy would remain.

Is this possible now, or does it require a new feature?

**Comment by asadmash** [comment] 2024-01-29 13:22
I'm also facing this issue. Any parent tab should be moved individually when the tree is in expended mode.

**Comment by mxmilkiib** [comment] 2024-03-03 11:25
dupe of #511

**Comment by mbnuqw** [comment] 2024-03-19 06:09
Closing this as a duplicate

**Closed as completed by mbnuqw** 2024-03-19 06:09 UTC
Labels: type: duplicate
