### ISSUE TITLE
Sync snapshots

### ISSUE THREAD

**Issue by ThaDaVos** [mbnuqw/sidebery#814] opened 2022-10-24 11:17 UTC
## Description
It would be amazing if snapshots can be synced too - or sync the tabs and groups between two devices

**Comment by mbnuqw** [comment] 2022-10-25 08:44
It's impossible to sync snapshots because they may have too big size. Syncing of tabs is tracked in #54
Closing as a duplicate of #54

**Closed as completed by mbnuqw** 2022-10-25 08:44 UTC
Labels: type: duplicate
