### ISSUE TITLE
The sider panel takes nearly 20%cpu

### ISSUE THREAD

**Issue by morning-start** [mbnuqw/sidebery#1428] opened 2024-01-24 05:08 UTC
The sider take many cpu, even nothing changed.

![插件](https://github.com/mbnuqw/sidebery/assets/76601464/36da5739-77f8-4e3e-b3ec-19e1e32583a8)

**Comment by andrevmatos** [comment] 2024-01-24 14:49
Yes, hitting this on NixOS + KDE + Wayland on Firefox Flatpak as well.
Started after Firefox v122.0 update

**Comment by mbnuqw** [comment] 2024-01-24 15:04
Reason: From v122, Firefox uses lots of CPU on animations and history panel has animation because of incorrect initial state.
Temporary solution: Remove history panel.
Fix: af2dc98632cedb9ea24542bd5bbf3a57b8cef509 (I'll release it soon)
Duplicate of #1388

**Closed as completed by mbnuqw** 2024-01-24 15:04 UTC
Labels: type: duplicate
