### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by marioPS** [mbnuqw/sidebery#934] opened 2023-02-10 22:14 UTC
Just a quick request to have the ability to select a range and sort: chronologically, by site, by keyword.

If this feature exists & I missed it, please call me a dickhead & point me in the right direction.

Ta!

Mikey

**Comment by mbnuqw** [comment] 2023-02-12 10:17
Duplicate of #643

**Closed as completed by mbnuqw** 2023-02-12 10:17 UTC
Labels: type: duplicate
