### ISSUE TITLE
[FR] Create tree structure by domain name option

### ISSUE THREAD

**Issue by devgid** [mbnuqw/sidebery#1491] opened 2024-02-29 15:16 UTC
## Description
Add option to sort alphabetically and regroup by domain name

Sometimes you might get the app crashed or you just have too many open tabs and you want to close the domains you are not interested and save the ones you want to keep for later.

Then if you could regroup your tabs (they still stays in their original panels) so it is is sorted by domain name and the same domains are in a 1 level tree structure. 

This is also useful if the extension restores the tabs flat when firefox crashed. That will give you an option to sort by domain name to try manage them.

**Comment by JohnVKRDam** [comment] 2024-03-03 17:49
A new option for sorting is going to be released (in a nightly build first). It would allow you to sort on Url.
**Sort Tabs by URL, Title, CreationTime:** https://github.com/mbnuqw/sidebery/issues/643#issuecomment-1975215661

That would (partly) solve your problem, right?

I know it is not exactly the same as sorting on the actual domain name and it won't create "domain groups", but it is pretty close. At the very least you will get sorted groupings of "https://www.domain-name.com", "https://domain-name.com", and ""https://sub.domain-name.com". So, managing/deleting them would be easy, or at least, easier  :-)

Maybe that helps?

I do agree that a sort option using the actual domain name itself would be really helpful. But it may be hard or even impossible to code.

**Comment by devgid** [comment] 2024-03-04 01:04
@JohnVKRDam yes that sorting would be just as good.

Sorting or grouping by domain is not that hard if you use regex expression to isolate the domain name from the URL. Many other extensions do that like adblocker or darkdreader allow certain domains to be whitelisted using this technique.

**Comment by mbnuqw** [comment] 2024-03-31 09:08
Duplicate of #56

**Closed as completed by mbnuqw** 2024-03-31 09:08 UTC
Labels: type: duplicate
