### ISSUE TITLE
[Bug] "Skip Grouped" Mouse Scroll Option Unfolds Parent

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#610] opened 2022-04-20 05:05 UTC
## Steps to reproduce
1. Enable "Skip folded tabs"
2. Fold tabs
3. Use mouse scroll to scroll through tabs
4. Observe that folded groups/tabs become unfolded and are not skipped

## Expected behavior
Folded groups/tabs are skipped and not unfolded

## Actual behavior
Folded groups/tabs are not skipped and are unfolded automatically activating the parent

### Addon data
<details><code>
{
  "settings": {
    "version": "4.10.0",
    "nativeScrollbars": false,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "reinit",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "rm_all",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 500,
    "dndTabActMod": "none",
    "dndExp": "hover",
    "dndExpDelay": 50,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "any",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "end",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "xl",
    "bgNoise": true,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": true,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "tabDoubleClick": "duplicate",
    "tabLongLeftClick": "new_after",
    "tabLongRightClick": "new_child",
    "tabsPanelLeftClickAction": "expand",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "rm_act_tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": true,
    "actualAllUrls": false,
    "actualTabHide": true
  },
  "storage": {
    "size": "225.1 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "1.2 kb",
      "expandedBookmarks": "114 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "9.5 kb",
      "favicons": "208.1 kb",
      "panelIndex": "1 b",
      "panels_v4": "445 b",
      "prevTabsData_v4": "872 b",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "tabsData_v4": "883 b",
      "tabsMenu": "395 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": true,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-11",
      "name": 3,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 8
    }
  ],
  "tabsMenu": [
    "undoRmTab",
    "mute",
    "bookmark",
    "reload",
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    [
      {
        "name": "Close"
      },
      "close",
      "closeDescendants",
      "closeTabsAbove",
      "closeTabsBelow",
      "closeOtherTabs"
    ]
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 15,
    "foldersCount": 9,
    "separatorsCount": 1,
    "maxDepth": 3
  }
}
</code></details>

### Logs
<details><code>
n/a
</code></details>

**Comment by cluxter** [comment] 2022-04-20 11:48
What's your version of Firefox?

**Comment by megamorphg** [comment] 2022-04-20 13:12
@cluxter 99.0.1 (64-bit)

**Comment by cluxter** [comment] 2022-04-20 14:13
It may be related to https://github.com/mbnuqw/sidebery/issues/607.
Can you try on a version 97 of Firefox?

**Comment by megamorphg** [comment] 2022-04-20 15:15
@cluxter I don't think this is critical enough for me to downgrade but just FYI, this issue also occurs with the latest version of v5:
![2022-04-20-0812-41](https://user-images.githubusercontent.com/1782353/164264162-51904632-2af8-4e0c-8168-f9d1a608cbe8.gif)

**Comment by mbnuqw** [comment] 2022-04-20 15:56
@megamorphg it's not a bug, it's the option "Auto expand tab on activation" in the "Sidebery Settings / Tabs tree" section.

**Comment by megamorphg** [comment] 2022-04-20 16:21
@mbnuqw ah, that makes sense. I disabled that.
The "Skip Grouped" sounds like it should skip grouped tabs which it still doesn't do.
Additionally, if scrolling within a group, it would skip groups inside of that group.

If one tries to scroll out of the group then there are two possibilities: users that want to do cyclic scrolling within the group and users that want to exit the group when scrolling past last child. So it could be an extra option for the "Cyclically."
Practically speaking I would want the 1st option because I have a group for a project, I would want to stay within the project (not go to the next project).

**Comment by mbnuqw** [comment] 2022-04-20 16:47
Anyway, I'm closing this issue since it resolved.

**Closed by mbnuqw** 2022-04-20 16:47 UTC

**Comment by megamorphg** [comment] 2022-04-20 17:05
@mbnuqw ah ok so what exactly is the Skip Grouped supposed to do? I thought it would at least skip the children:
![image](https://user-images.githubusercontent.com/1782353/164284500-f2e4b36c-fbd5-4a0a-8b34-f24cac69ac87.png)

**Comment by megamorphg** [comment] 2022-04-20 17:23
Ah no, it's accurate enough. I've been calling it the wrong thing whole time. This works awesome, Vivaldi can't do this.
