### ISSUE TITLE
add an option to not create new panels for container tabs

### ISSUE THREAD

**Issue by pointfourone** [mbnuqw/sidebery#108] opened 2019-11-24 20:10 UTC
## Description
I don't want different panels in the same window for different container tabs. I'd like all the tabs in a single panel. There can an option to color a container tab to highlight it.

Using different panels make me forget about where my pages are and if a parent non-container tab opens a child container tab, the child tab is separated from the parent which breaks my workflow and concentration.

**Comment by mbnuqw** [comment] 2019-11-25 14:14
This will be possible in the next version:

![screenshot-2019-11-25 19:03:45](https://user-images.githubusercontent.com/6276694/69546864-5acbed80-0fb6-11ea-902b-fcb19c0a41f6.png)

**Comment by mbnuqw** [comment] 2019-11-25 14:15
Closing this as a duplicate of #83

**Closed by mbnuqw** 2019-11-25 14:15 UTC
Labels: enhancement
