### ISSUE TITLE
Move tabs with certain URL into groups, not just panels

### ISSUE THREAD

**Issue by brohangutenburg** [mbnuqw/sidebery#1569] opened 2024-04-03 05:24 UTC
### Description

It's funny I was reading [this](https://github.com/mbnuqw/sidebery/issues/62) issue, and even though the OP wasn't looking for what I'm talking about, @mbnuqw thought he was lol.

Basically, I'd love to see a feature where certain URLs are moved into specific _groups_ not just tabs.

I have my panels all set up, production jumps into a certain panel, sandboxes jump into another, research into a third, and the last one is for work communication (gmail, slack, gchat, etc). I would love to be able to further organize my research panel so that reddit threads jump into a group in that panel, githubs into another, stackexchange into another, etc. 

Also, the same thing for certain window instances would be amazing but I'm sure impossible. However, it would be cool if there was one instance of a certain panel across multiple windows  then a tab would jump into that panel. For example, if I have a browser window open on each monitor, but only one of them has my "Work Communication" panel open, the the tab would jump into the panel on _that_ window

**Comment by mbnuqw** [comment] 2024-04-03 11:51
Duplicate of #292.
For moving tabs of the same panel between windows track #1290.

**Closed as completed by mbnuqw** 2024-04-03 11:51 UTC
Labels: type: duplicate
