### ISSUE TITLE
Middle click on "new tab" button should open child tab beneath the active one

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#752] opened 2022-09-09 00:10 UTC
## Description
Currently you can click "New tab" button on the bottom of tabs list to open new level 0 tab, and you can right click to choose the container. Would be great if you could also middle click on button to open new child tab, e.g. you're currently on level 0 tab, and it will open level 1 tab beneath it.

**Comment by dexeonify** [comment] 2022-09-09 09:53
<kbd>Ctrl</kbd>+Left click does that. Probably one of Sidebery hidden mouse shortcuts. Would be nice if we can define shortcuts for <kbd>Shift</kbd>+Left click or middle click new tab too.

**Comment by emvaized** [comment] 2022-09-09 12:55
Thanks, I know about `Ctrl` + Left click. My point is that it would be great to have it on middle click as well, so that it won't require to reach out for keyboard. 
It also makes sense since everywhere through out the system middle click usually behaves as `Ctrl` + Left click.

**Comment by emvaized** [comment] 2022-09-09 14:26
It seems that in current version middle click on 'new tab' button calls "[reopen()](https://github.com/emvaized/sidebery/blob/a28eec1bd8f48039dabd95e72701b8ca23582e7e/src/sidebar/components/bar.new-tab.vue#L133)" function, which, I guess by name, should reopen last closed tab, or reopen current tab. 

But in my case this action just does nothing. 
@dexeonify Does it do anything for you, when you middle click on 'new tab' button?

**Comment by dexeonify** [comment] 2022-09-09 15:33
> But in my case this action just does nothing. @dexeonify Does it do anything for you, when you middle click on 'new tab' button?

No, which is why I suggested:
> Would be nice if we can define shortcuts for <kbd>Shift</kbd>+Left click or middle click new tab too.

But now that you mention it, I do remember a commit regarding middle-clicking and alt-clicking the new tab button. I can't seem to find it now.

**Comment by dexeonify** [comment] 2022-09-09 15:39
Ah yes, it's these two commits: mbnuqw/sidebery@0aef672 and mbnuqw/sidebery@7a13a06. Both don't seem to work, might be a regression somewhere.

**Comment by emvaized** [comment] 2022-09-09 15:43
I think, middle click with no modifiers on this button should create new child tab, as `Ctrl` + Left click is already assigned to do it, and it is common convention in all apps including Firefox that middle click should behave the same as `Ctrl` + Left click. 

And maybe, should use `Alt` + Left click to reopen tab?

**Comment by emvaized** [comment] 2022-09-09 15:46
I can create pull request about it. But non-working `reopen()` function would be another thing to deal with.

**Comment by mbnuqw** [comment] 2022-09-18 07:09
Middle click on the "new tab" button works as intended - it reopens an active tab in configured container or updates url to configured one.

https://user-images.githubusercontent.com/6276694/190889812-d15d8065-2126-4b30-a732-a1691297215c.mp4

I just more often use reopening tabs in different container than opening new child, but I agree that this behavior should be configurable (with the "child tab" option as default)

**Comment by mbnuqw** [comment] 2022-09-19 13:19
Resolved in [b26](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0b26)

**Closed as completed by mbnuqw** 2022-09-19 13:19 UTC
Labels: type: bug, reproduced: yes
