### ISSUE TITLE
Sideberry Not Restoring Tabs in Respective Containers on Firefox Startup when "Browsing & Download History" Cleanup Enabled

### ISSUE THREAD

**Issue by akhiljalagam** [mbnuqw/sidebery#1154] opened 2023-08-05 06:43 UTC
**Issue Description:**
When I enable the "Cleanup of Browsing & Download History" option on Firefox close, Sideberry fails to restore tabs at all upon browser startup. Additionally, attempting to restore snapshots does not open the tabs in their respective containers; instead, they all open in the default container.

**Steps to Reproduce:**
1. Install Sideberry and configure tab containers in Firefox.
2. Enable the "Cleanup of Browsing & Download History" option in Firefox settings.
3. Close Firefox and reopen it to observe that Sideberry does not restore tabs in any panels.
4. Attempt to restore snapshots through Sideberry and notice that the tabs still open in the default container.

**Expected Behavior:**
When the "Cleanup of Browsing & Download History" option is enabled, Sideberry should still be able to restore tabs in their respective containers upon Firefox startup. Additionally, restoring snapshots should open the tabs in the containers they were originally saved in.

**Temporary Workaround:**
To avoid this issue, I have currently disabled the "Browsing & Download History" cleanup on Firefox close. Instead, I am using the "History Cleaner" extension, which automatically cleans up browsing history older than X days when Firefox is idle for 60 seconds.

**Environment:**
- Operating System: Void Linux
- Firefox Version: firefox-114.0_1
- Sideberry Version: Beta (v5.0.0rc4)

Please let me know if you require any further information or need assistance in resolving this issue.

**Despite the issue mentioned above, I want to acknowledge the developer's hard work and dedication in creating such a useful tool. Your efforts have undoubtedly made a positive impact on countless users like me.**

**Thank you for your dedication to maintaining and improving Sideberry. I am looking forward to future updates and fixes that will make the extension even better. Keep up the great work!**

**Comment by mbnuqw** [comment] 2023-08-05 10:09
This issue covers two unrelated cases:
- Initialization behavior

  Sidebery works as intended because on initialization it uses the list of tabs provided by Firefox, and when you enable "Cleanup of Browsing & Download History" this list is empty every time you launch the browser. It's a duplicate of #693.

- Restoring a snapshot

  It's a bug that will be fixed in rc5, thanks for reporting!

**Comment by akhiljalagam** [comment] 2023-08-05 11:26
Thank you for explaining the two cases.

1. Initialization behavior: I understand now that Sidebery relies on Firefox's tab list, which becomes empty when "Cleanup of Browsing & Download History" is enabled. I see that this is already reported as a duplicate of issue #693. I'll follow the updates there.

2. Restoring a snapshot: Great to know this will be fixed in rc5. Looking forward to the update!

**Comment by mbnuqw** [comment] 2023-09-20 09:14
Resolved in v5.0.0

**Closed as completed by mbnuqw** 2023-09-20 09:14 UTC
Labels: type: bug, reproduced: yes
