### ISSUE TITLE
Alt+9 goes to last tab in last panel instead of current one

### ISSUE THREAD

**Issue by Vinnl** [mbnuqw/sidebery#395] opened 2021-05-15 10:23 UTC
## Steps to reproduce

1. Create more than one panel.
2. View a tab in a panel other than the last one.
3. Press Alt+9

## Expected behavior

Focus moves to the last tab in the current panel.

## Actual behavior

Focus moves to the last tab in the last panel.

## Environment info

OS:  linux (Ubuntu 20.04)
Firefox version:  88.0.1
Addon version:  4.9.4

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "left",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": true,
    "actualAllUrls": false,
    "actualTabHide": true
  },
  "storage": {
    "size": "372.9 kb",
    "props": {
      "containers_v4": "5.5 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "2.4 kb",
      "favicons": "351.1 kb",
      "panelIndex": "1 b",
      "panels_v4": "1.9 kb",
      "prevTabsData_v4": "4.1 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "4.7 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "KMQxXEviGDiV",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "mAG8R_ZdSrCV",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "5thJ-F0ry5CV",
      "name": 5,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "DfW9duJQIpDV",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "rgjV4eZQ9-BV",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-10227",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10228",
      "name": 11,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10229",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10230",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10231",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10232",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10233",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10328",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-19134",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-21920",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-37401",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-37880",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-37981",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38000",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38011",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38078",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38326",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38350",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38376",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38380",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38410",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 36
    }
  ],
  "bookmarks": {
    "bookmarksCount": 116,
    "foldersCount": 11,
    "separatorsCount": 3,
    "maxDepth": 2
  }
}
</code></details>

**Comment by Vinnl** [comment] 2021-05-15 11:20
As a workaround, enabling "Hide tabs of inactive panels" in the Tabs section in settings will also result in this behaviour.

**Comment by mbnuqw** [comment] 2021-05-27 18:04
Alt+9 is not part of sidebery and from Firefox perspective everything works as intended - The last tab activated, so I'm closing this issue.

If you want you can open another issue (feature request) to add in-sidebery keyboard shortcut to "activate last tab on the current panel" and I'll add this later.

**Closed by mbnuqw** 2021-05-27 18:04 UTC
