### ISSUE TITLE
Broken: After closing current tab activate - none

### ISSUE THREAD

**Issue by ProCycleDev** [mbnuqw/sidebery#500] opened 2021-10-22 21:02 UTC
I have a lot of tabs. And a lot of groups. Frequently most of those tabs are not loaded (inactive). When I close the tab I'm currently working on the view often jumps to a different group or scrolls all over the place. I didn't want this behavior so I turned it off. But the setting doesn't work and the tab list still jumps around. For reference see TreeTabs default behavior.

## Steps to reproduce
Settings -> Tabs -> After closing current tab activate
Set to none
Have multiple tabs open in different groups
Close a tab

## Expected behavior
Tab closes. View of tabs does not scroll or switch groups

## Actual behavior
Tab closes. A predetermined tab is activated and is scrolled to or groups switch

## Environment info

OS:  Windows 10, Ubuntu 20.04
Firefox version:  93.0
Addon version:  4.9.4

<details><code>

{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "any",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "none",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 1,
    "snapIntervalUnit": "day",
    "snapLimit": 30,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "new_child",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "RYAN-HOVLAND",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "56.7 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "expandedBookmarks": "18 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "23.1 kb",
      "favicons": "1.1 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.6 mb",
      "prevTabsData_v4": "125.2 kb",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "snapshots_v4": "53.7 mb",
      "tabsData_v4": "124.7 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "z2Fb6Sn-HW1b",
      "name": 14,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "5OBdkhqVIZ3b",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": 20141,
      "customIcon": 20141,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "a8NGOY1Dr40b",
      "name": 8,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Mty4d9dlNN3b",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": 2171,
      "customIcon": 2170,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "pEtsz-kU0l1b",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": 399541,
      "customIcon": 399541,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "HjzPBxoPy8zT",
      "name": 14,
      "icon": "...",
      "color": "...",
      "customIconSrc": 399541,
      "customIcon": 399541,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "dtfyjfLZIRiq",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": 17126,
      "customIcon": 17126,
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "6JJAnd_UW-iq",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "1PB4iaqJ0D0b",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "mFe-uUic0cMT",
      "name": 7,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1140
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 1122,
    "foldersCount": 86,
    "separatorsCount": 1,
    "maxDepth": 5
  }
}
</code></details>

**Comment by pintassilgo** [comment] 2021-11-02 04:15
`none` means *not controlled by the addon, let Firefox choose the tab to activate*. I think it's working as expected.


> When I close the tab I'm currently working on the view often [...] scrolls all over the place. For reference see TreeTabs default behavior.

I installed Tree Tabs. Opened dozens of tabs so that scrollbar exists. Selected a tab from the top ("Tab A"). Opened a new tab with Ctrl+T. Closed the new tab with Ctrl+W. Tab A was activated again and sidebar, as expected, scrolled to top. Exactly the same as Sidebery when set to `none`.

**Comment by br4nnigan** [comment] 2023-02-18 10:44
>  Frequently most of those tabs are not loaded (inactive). 

I suggest setting `Ignore discarded tabs` to `off` so that the actual previous/next tab is activated. Discarded means not loaded. 

Personally I'd prefer if `off` would actually mean that just a blank space is shown, especially since `previous tab` combined with `Ignore discarded tabs` equals the default behavior and thus `off` is a bit redundant.

**Comment by mbnuqw** [comment] 2024-03-18 12:48
Expected behavior of "After closing current tab activate: none"

**Closed by mbnuqw** 2024-03-18 12:48 UTC
