### ISSUE TITLE
Search in panel

### ISSUE THREAD

**Issue by a-mann** [mbnuqw/sidebery#344] opened 2021-02-22 07:49 UTC
I think searching by tab name or address inside the panel will be very useful. With highlighting of results or grouping of results found at the top of the panel.
Thanks for the great addon.

**Comment by grravity** [comment] 2021-03-18 00:56
Came here to suggest this, a simple search bar for bookmarks and tabs would be a really nice addition I'd like to see.

**Comment by mbnuqw** [comment] 2021-03-27 15:14
Working on this (will be in v5)
Duplicate of #168

**Closed by mbnuqw** 2021-03-27 15:14 UTC
