### ISSUE TITLE
panel icon customization not working

### ISSUE THREAD

**Issue by boldcompany** [mbnuqw/sidebery#480] opened 2021-09-27 22:06 UTC
## Steps to reproduce
(a) Enter a URL for a custom icon; or
(b) Enter text and values per suggested syntax.

## Expected behavior
A custom icon will appear for the intended panel.

## Actual behavior
In the (a) case above, the icon is shown in the panel editing screen. However, that icon is never applied to the actual panel in the Sidebery sidebar.
In the (b) case above, text can be entered and a font specified, but HTML colors do not seem to work (nor any of a variety of color encodings tried).

## Environment info

OS:  Windows
Firefox version:  92.0.1
Addon version:  current

**Comment by linuxiorr** [comment] 2022-07-01 17:03
I'm experiencing this issue as well. To be precise, I'm talking about the (a) case as outlined by boldcompany.

OS: Fedora
Firefox version: 102.0
Addon version: 4.10.1 (the current one from the Mozilla addon website)

**Comment by yuyuko233** [comment] 2022-09-14 03:36
> I'm experiencing this issue as well. To be precise, I'm talking about the (a) case as outlined by boldcompany.
> 
> OS: Fedora Firefox version: 102.0 Addon version: 4.10.1 (the current one from the Mozilla addon website)

me too.

**Comment by mbnuqw** [comment] 2022-10-03 11:47
Duplicate of #129

**Closed by mbnuqw** 2022-10-03 11:47 UTC
