### ISSUE TITLE
Cannot to close multiple tabs

### ISSUE THREAD

**Issue by vitonsky** [mbnuqw/sidebery#1441] opened 2024-01-31 23:14 UTC
Hi, i tried your addon recently, when TST addon broken with new update. My current experience is awesome, I like snapshots in your solution, I like panels and unload feature. Big up for your work, it makes management a lot of tabs for research are comfortable as never before!

I think i will use your solution a long time, especially because TST failed up a loud, for me as developer they shown unacceptable low quality level, when they rolled out a new release with no testing and kicked up their users. I hope we all learned the lesson to test our products thoroughly before release. And i hope your extension will not kick us in future, because now you are my favorite.

I found one important bug that break my experience for research sessions. I cannot to close all selected tabs by hotkeys or with mouse middle button click, it slow me down a bit.

## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Enable or disable option "Use multi-selection when closing tabs with middle-click"
- Click on any tab and then Shift + another tab to select multiple tabs
- Press `Ctrl+W` or middle button of mouse, to close selected tabs

## Expected behavior
- All selected tabs will be closed

## Actual behavior
- Only one tab will be closed
- No any reaction on toggle option "Use multi-selection when closing tabs with middle-click"

If i press right mouse button and then click "close" it works well for me, but it is too long for my explore flow where i can open a dozens tabs and then close it all for a short time.

**Comment by mbnuqw** [comment] 2024-02-01 11:39
To make `Ctrl+W` work, you need to enable "Highlight native tabs..." option (Sidebery settings / Tabs / Native (horizontal) tabs). The cause of this is that addons are not allowed to handle keyboard shortcuts used by Firefox. I also should note that this method will also close the active tab (in addition to the selected ones).

As an alternative, Sidebery has its own keybinding to close selected tabs (check out "Keybindings" in Sidebery settings).

**Comment by vitonsky** [comment] 2024-02-01 12:27
Now `Ctrl+W` really works fine, thank you. But i still can't close multiple tabs by middle-click.

**Comment by mbnuqw** [comment] 2024-02-01 12:42
Ah, sorry, got it now. The "Use multi-selection when closing tabs with middle-click" setting means the following workflow:
- You press the mouse-wheel (middle click)
- Move your cursor to select desired range of tabs
- And release the mouse-wheel button - Tabs in selected range are closing

**Comment by vitonsky** [comment] 2024-02-01 12:59
Oh, it looks i misunderstood this feature. Is it possible currently to select multiple tabs, then press mouse-wheel to close all selected tabs?

If it is not possible, can we convert current issue to a feature request? I believe it is important feature for people who have a lot of tabs and rely only on addon behavior.

My use case is research in internet. I may open a dozens and even hundreds tabs for a short time (few hours-few days) and then i close it, but i want to leave some of them, so i cherry-pick it with selection.

Currently it still possible to close selected tabs with right mouse button click and then press "close", but since it takes 2 clicks and one of them with high precision, this UX a bit break focus on explore the pages content. This feature are small, but important, because it uses frequently.

**Comment by mbnuqw** [comment] 2024-02-01 13:03
>  Is it possible currently to select multiple tabs, then press mouse-wheel to close all selected tabs?

No, only with context menu.

> If it is not possible, can we convert current issue to a feature request?

Sure

**Comment by mbnuqw** [comment] 2024-02-01 18:31
Actually, you're right. Closing (or unloading, depending on the setting) selected tabs with middle-click feels more intuitive. Remarking this issue as a bug and fixing it.

**Closed as completed** 2024-02-01 18:35 UTC
Labels: type: bug, reproduced: yes

**Comment by mbnuqw** [comment] 2024-02-04 19:12
It turned out that in sidebery v5.1.1 the problem persists if the "Use multi-selection when closing tabs with middle-click" setting is enabled. Fixed in [30afdfa](https://github.com/mbnuqw/sidebery/commit/30afdfada8d7365ec5b5f4c0cadb84b6f71f1879) (will be in the next after v5.1.1 release)

**Comment by llc0930** [comment] 2024-02-09 13:56
So now after [30afdfa](https://github.com/mbnuqw/sidebery/commit/30afdfada8d7365ec5b5f4c0cadb84b6f71f1879), the "Use multi-selection when closing tabs with middle-click" setting is useless? The current actual behavior is like accepting multiple selections when the middle click is used to unload or close tabs. If so, then there is no need for me to add adjustments to this option in the next translation revision. Because maybe it and its notes should be deleted?

**Comment by mbnuqw** [comment] 2024-02-09 14:33
@llc0930, No, the setting is working as usual - defining a range of tabs with middle-button pressed and closing them with releasing the button (I'll update that note for more clarity). What didn't work was a simple middle-click on multiple already selected tabs when the above setting was enabled - configured action (e.g. close/unload) only applied to one, clicked tab. And that was fixed in 30afdfa.

**Comment by llc0930** [comment] 2024-02-09 15:02
@mbnuqw, Got it, so this feature doesn't actually affect on multiple already selected tabs. My middle mouse button microswitch has a bad contact, so I really only try to middle click on multiple already selected tabs.
