### ISSUE TITLE
[FeatureRequest] Open loaded/unloaded Tab Count in Extension Icon

### ISSUE THREAD

**Issue by arvind-gr** [mbnuqw/sidebery#641] opened 2022-05-28 13:09 UTC
## Description

I was using this addon and found your addon super handy. Can you consider adding total loaded/unloaded Tabs count in the Extension icon not just in sidebar?
Example https://addons.mozilla.org/en-GB/firefox/addon/tab-tally/ 
Or this https://addons.mozilla.org/en-GB/firefox/addon/open-tab-count-resurrected 

![image](https://user-images.githubusercontent.com/12880765/170826939-b02f048a-2805-4cb2-8ff2-512f23ce0cc7.png)

**Comment by mbnuqw** [comment] 2022-05-28 13:56
Duplicate of #378

**Closed by mbnuqw** 2022-05-28 13:56 UTC
Labels: type: duplicate
