### ISSUE TITLE
Cmd-click to open in new tab

### ISSUE THREAD

**Issue by mhillebrand** [mbnuqw/sidebery#573] opened 2022-02-13 18:58 UTC
I'd really like the ability to open a bookmark in the current tab **_and_** to open a bookmark in a new tab when Command-clicking on macOS (or Ctrl-clicking on Linux/Windows). I also noticed that Sidebery will gladly open bookmarks in pinned tabs without respecting the purpose of pinned tabs.

Currently, it's all or nothing with respect to opening in a new tab or not—regardless of the Command key being held in while clicking. 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/286198/153770317-f35ca449-9681-41e2-bd5e-db68fe164fd5.png">

Loving this add-on so far! Thank you.

**Comment by Mostha** [comment] 2022-02-26 20:10
There is no plusz button for opening a new tab in te list of  tabs on the side at end of the list or the biging after the pinned tabs.

**Comment by dexeonify** [comment] 2022-03-01 08:33
> There is no plusz button for opening a new tab in te list of tabs on the side at end of the list or the biging after the pinned tabs. Other ethen the ctlr-t command combination.I would like too a visual one with a big plusz that is always trhere to see and opens a new tab,and well on the right clixk menu of this addon until then i use another one that has that.

You are looking for #286. This is not the correct issue. FWIW it's available in the v5 branch.

**Comment by mbnuqw** [comment] 2024-03-10 08:57
Closing as a duplicate of #396

**Closed by mbnuqw** 2024-03-10 08:57 UTC
