### ISSUE TITLE
[Feature Request] Independent Movement of Expanded Parent Tabs in Sidebery Tree Structure

### ISSUE THREAD

**Issue by asadmash** [mbnuqw/sidebery#1436] opened 2024-01-29 13:12 UTC
Independent Movement of Expanded Parent Tabs in Sidebery Tree Structure

Summary:

This issue proposes a feature enhancement to Sidebery's tree structure, allowing independent movement of parent tabs when they are expanded. Currently, moving a parent tab in the tree also moves all its child tabs, regardless of whether the parent tab is collapsed or expanded. This feature request suggests an improvement where:

    Collapsed Parent Tabs: Moving a collapsed parent tab should continue to move all its child tabs along with it, as this behavior maintains consistency and aligns with user expectations.
    Expanded Parent Tabs: When a parent tab is expanded, it should be possible to move the parent tab independently without affecting its child tabs. This would grant users greater flexibility in organizing their tabs and managing large, complex projects.

Problem:

    The current behavior of moving all child tabs with the parent tab can be inconvenient, especially when working with expanded parent tabs containing numerous child tabs.
    This limitation hampers efficient workflow and limits users' ability to organize and access specific child tabs within large branches.

**Comment by devgid** [comment] 2024-02-09 16:16
Duplicate: https://github.com/mbnuqw/sidebery/issues/1430

**Comment by mbnuqw** [comment] 2024-03-31 06:33
Duplicate of #511

**Closed as completed by mbnuqw** 2024-03-31 06:33 UTC
Labels: type: duplicate
