### ISSUE TITLE
Ability to move a card to a group rather than just a panel for easy management of groups on the main panel

### ISSUE THREAD

**Issue by macgyverkam** [mbnuqw/sidebery#1356] opened 2023-11-16 07:29 UTC
Is it possible to move a card to a group rather than just a panel to easily manage groups on the main panel

![image](https://github.com/mbnuqw/sidebery/assets/18258356/2c100e97-f4bb-4577-82b9-9916021c088d)

**Comment by mbnuqw** [comment] 2024-03-28 15:18
Duplicate of #1109

**Closed as completed by mbnuqw** 2024-03-28 15:18 UTC
Labels: type: duplicate
