### ISSUE TITLE
Activate scrolling by hovering over any tab

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [mbnuqw/sidebery#67] opened 2019-07-26 16:20 UTC
In Sidebery, unless the **Use native scroll-bars** optional setting is turned on, the only way to scroll tabs is to first of all click on a tab. It would be useful to be able to activate scrolling of tabs by hovering over any tab in Sidebery. Tree Style Tab has an addon called [Hoverswitch](https://addons.mozilla.org/en-GB/firefox/addon/tst-hoverswitch/) that allows you to switch tabs by hovering over them (i.e. moving the cursor over any tab). The functionality of that Tree Style Tab addon could be adapted so that instead of switching tabs, moving the cursor over tabs activates scrolling via the arrow keys.

The **Use native scroll-bars** configuration when turned on can be distracting because it does not fade into the background when not in use so it takes up unnecessary space and causes visual noise. Therefore activating scrolling when the mouse cursor is detected on any tab would be a more effective way to activate scrolling than the current click to scroll approach

**Comment by mbnuqw** [comment] 2019-07-26 18:45
I cannot reproduce this behavior. I can freely scroll list of overflowed tabs without any extra click. I have this issue on some FirefoxNightly build (iirc: https://bugzilla.mozilla.org/show_bug.cgi?id=1536730), but this is fixed now. Can you please write your version of Firefox? Thanks

**Comment by ChukwuemezieChristopherAneke** [comment] 2019-07-26 21:00
Interesting, I assumed click to scroll was normal. Glad to know it's a bug, my version of Firefox is `Mozilla Firefox 67.0.2`

**Comment by mbnuqw** [comment] 2020-04-22 05:29
Closing this as an unreproducible. @ChukwuemezieChristopherAneke or anybody else, please, reopen if issue still present.

**Closed by mbnuqw** 2020-04-22 05:29 UTC
Labels: bug
