### ISSUE TITLE
Slow deletion of a group of tabs

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#209] opened 2020-04-23 02:45 UTC
Currently, deleting selected tabs is like this: after deleting each tab, the panel is redrawn. This greatly slows down deletion, especially when there are a large number of tabs being deleted. Is it possible to make the deletion of the tab group like this: delete all tabs and only then redraw the panel?

**Comment by mbnuqw** [comment] 2020-04-23 17:10
If you close selected tabs with the default Firefox shortcut "Ctrl+W" (or "Cmd+W"), sidebery will not be able to recognize this action and will just react on the "onRemoved" event for each tab.

But if you use another method of deletion, please, describe this method and write what settings you are using (debug info).

**Comment by Dook1** [comment] 2020-04-23 17:19
Right click on the sidebery panel=>close.

[Sidebery _ Settings.txt](https://github.com/mbnuqw/sidebery/files/4524092/Sidebery._.Settings.txt)

**Comment by mbnuqw** [comment] 2020-04-23 17:22
Thank you for clarification, this looks like a bug...

**Comment by mbnuqw** [comment] 2020-04-25 13:12
Cannot reproduce this behavior. I've tested deleting of ~100 selected tabs in flat/tree layout, in deferent panels and with different methods. And for all these test cases the whole process of closing was around 1 sec.

Internally, before call the API function Sidebery marks all these tabs as hidden, to momentary hide them from the panel. But actual tabs are still in Sidebery's state and they will be completely removed only with "onRemoved" event from Firefox. This was done because some of the tabs can be blocked by confirmation dialog (or may not respond) and I need simple way to show them again.

So the process of removing multiple tabs should look like this:
- user removes tabs
- all selected tabs disappear from the panel << one re-rendering of the panel
- [internally] we are waiting for "onRemoved" events and removing tabs from the state << re-rendering of the counter of tabs in navigation-bar

Could you answer the following questions:
- Do you see sequential "removing" of each tab on the panel (one by one)?
- How many tabs do you delete and how long does this operation take?
- Does this always happen, or sometimes?
- Does this happen after disabling other addons?

**Comment by mbnuqw** [comment] 2020-04-25 16:12
Alright, no need to answer the questions - I finally can reproduce it. This happens (in my case) because Firefox starts the delete process with some delay and Sidebery thinks that these tabs are not responding or are showing the close dialog.

**Comment by Dook1** [comment] 2020-04-25 16:38
Is this a Firefox issue?

**Comment by mbnuqw** [comment] 2020-04-25 16:52
No, this can be fixed on my side, and I'll try to do this soon.

**Comment by mbnuqw** [comment] 2020-06-03 10:34
I've updated the process of removing multiple tabs. Could you check v4.9.0?

**Comment by Dook1** [comment] 2020-06-03 15:21
As quick as thought. Thanks. 
But after deleting the entire group of tabs, a tail appears for a split second (the last tab pops up, but disappears right away). I think this is related to some Timeout. But in principle, it does not bother.

**Comment by mbnuqw** [comment] 2020-06-06 18:03
Yep, there is a timeout to check if tabs were actually closed. And if there is closing tab blocked with confirmation dialog or Firefox was busy and didn't remove some tabs Sidebery will show them again. Unfortunately I cannot detect what case that was as well as predict how long Firefox will "freeze", so there's nothing more I can do here (I cannot infinitely increase that timeout b/c of confirm dialog case).

Closing this

**Closed by mbnuqw** 2020-06-06 18:03 UTC
Labels: bug
