### ISSUE TITLE
Some animations are called on hidden tabs, slowing extension down

### ISSUE THREAD

**Issue by Illiou** [mbnuqw/sidebery#1003] opened 2023-03-27 18:56 UTC
I did some performance profiling with v5.0.0b31 on the lastest Firefox with thousands of tabs open to try to find out why the extension is slowed down by a large number of tabs so much. It was difficult to pin down because it seems most of the slowdown happens inside Vue and it's rendering and I don't know enough about that to determine the cause. But I still did find two things:

1. Collapsing a branch is really slow with a lot of tabs open (contrary to expanding a branch) because there seems to exist some animation which is processed for every tab, visible or not, before the collapsing can be shown. After turning animations off in the settings collapsing is similarly quick to expanding. Maybe it could be changed such that the animation is not applied to all existing tabs.
2. When starting to drag a tab there is quite a long delay to when the tab starts moving along with the cursor with a lot of tabs open. Again I saw in the profiler that there seems to be some animation `drag-hover-fix` which is called on every tab, visible or not. After removing this animation the time of some `nsBaseDragService::InvokeDragSession` went from ~1s to ~270ms. I didn't see any difference in behavior so I'm not sure what the purpose of `pointer-events: none/auto` is here. But if it's necessary maybe it can be also changed to only be applied to relevant tabs.

**Comment by mbnuqw** [comment] 2023-06-12 16:13
Thanks for the report.

1. The problem is related with `TransitionGroup` component of Vue. There was performance issue even with all `transitions/animations` disabled, so I stopped rendering `TransitionGroup` when animations are turned off as a temp workaround (https://github.com/mbnuqw/sidebery/commit/7a1da4b040f2d3506993c198a8a096421f2e4b66). Anyway, this is a known issue and I'll return to it soon.
2. Should be fixed in the next release, thanks for pointing out!

**Comment by mbnuqw** [comment] 2023-07-11 20:26
Fixed in `rc1`

**Closed as completed by mbnuqw** 2023-07-11 20:26 UTC
Labels: reproduced: yes, type: perf
