### ISSUE TITLE
Open links from outside and new tabs in current default panel container

### ISSUE THREAD

**Issue by matteomorlack** [mbnuqw/sidebery#917] opened 2023-01-30 10:11 UTC
A feature that i would really like is the ability to open a new tab (from "+" button on firefox native tabs bar) and links from outside firefox with the default container for the currently open panel. This is similar to what Simple Tab Groups is currently doing.

**Comment by mbnuqw** [comment] 2023-01-31 20:50
This is a planned feature/bug-fix for v5.
Closing as a duplicate of #305

**Closed as completed by mbnuqw** 2023-01-31 20:50 UTC
Labels: type: duplicate
