### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by Z2Flow** [mbnuqw/sidebery#892] opened 2023-01-10 18:51 UTC
## Description
Please add a close button for each listed open tab.
Having to right-click and then choose "close" is a pain when closing more than one tab.

**Comment by albino1** [comment] 2023-01-11 05:50
In the Settings turn on `Show close button on mouse hover`.

**Comment by mbnuqw** [comment] 2023-01-20 16:22
Duplicate of #217

**Closed as completed by mbnuqw** 2023-01-20 16:22 UTC
Labels: type: duplicate
