### ISSUE TITLE
additional browsing functions in the Sidebery panel

### ISSUE THREAD

**Issue by yotamguttman** [mbnuqw/sidebery#1536] opened 2024-03-24 10:14 UTC
### Description

hi! did you consider adding an option to enable a URL bar in the Sidebery sidebar (as well as back/forward and reload buttons)?

then, users could use Sidebery (along with a bit of userchrome.css) to achieve a very minimal look for Firefox. something similar to Arc Browser but more secure :)
![image](https://github.com/mbnuqw/sidebery/assets/92977002/375d227d-4e8b-4526-93a0-e56fcdeee944)
 
I think it's relevant to Sidebery userbase because Sidebery's philosophy is utilising the vertical usability of the UI, as opposed to the conventional horizontal approach. if Sidebery was given the additional browsing options, it could provide a solution for users to replace everything that the horizontal panel currently offers and make it redundant. then users would be able to customise the UI to have the webpage stretch top to bottom and rely solely on Sidebery for browsing! considering that Sidebery already offers an exceptional bookmark library and history browsing capabilities. that's everything we need!

looking forwards to hearing what you think :)

**Comment by yotamguttman** [comment] 2024-03-24 10:50
made quick mockups in Penpot :)

this is what it could look like off the bat:
![ui](https://github.com/mbnuqw/sidebery/assets/92977002/66d75eda-f4d9-407b-aca6-e0af31b04185)

and if you customise the browser's UI via userchrome.css:
![userchrome](https://github.com/mbnuqw/sidebery/assets/92977002/68548805-86e3-4eba-9b09-8e93610e386b)

**Comment by mbnuqw** [comment] 2024-03-26 11:31
Duplicate of #1127 and wontfix

**Closed as completed by mbnuqw** 2024-03-26 11:31 UTC
Labels: type: duplicate
