### ISSUE TITLE
Tabs are reloaded when moved from one panel to another

### ISSUE THREAD

**Issue by Keagel** [mbnuqw/sidebery#227] opened 2020-05-08 08:34 UTC
## Steps to reproduce

- Create two panels
- Open a few tabs in one panel
- Move them to another panel

## Expected behavior

Tabs are moved without reloading. If the tabs are already loaded, they should stay loaded without reloading. If they are discarded, they should stay discarded too.

## Actual behavior

Tabs are moved and are reloaded, no matter their current state.

**Comment by mbnuqw** [comment] 2020-05-10 19:22
If the moved tab reloaded in another container, the cause of this may be the "Container of the new tab" option in panels configs (this will be fixed). If not, please, provide debug info (Sidebery settings / Help / Show debug info).

**Comment by Keagel** [comment] 2020-05-10 20:26
You're right, this is what happened. Moving tabs to a panel that's not assigned to a container doesn't do that.

**Comment by mbnuqw** [comment] 2020-06-03 10:34
Fixed in v4.9.0

**Closed by mbnuqw** 2020-06-03 10:34 UTC
Labels: bug
