### ISSUE TITLE
Switch pane anywhere with shift + scroll

### ISSUE THREAD

**Issue by Akryum** [mbnuqw/sidebery#1258] opened 2023-09-23 19:37 UTC
## Description

Be able to switch between panes anywhere in the sidebar with Shift + Mouse wheel scroll.

**Comment by P-a-d-r-a-i-g** [comment] 2024-02-08 14:35
Duplicate of
[Feature Request] Shift+Scroll on anywhere within sidebar (or just empty space) to switch between panels #986

**Closed as completed** 2024-03-11 10:52 UTC
Labels: type: duplicate
