### ISSUE TITLE
Feature request: dynamic tab panels

### ISSUE THREAD

**Issue by flexagoon** [mbnuqw/sidebery#1066] opened 2023-06-05 08:56 UTC
## Description

Currently, you need to manually create panels in order to switch between them. I'd like to have dynamic panels functionality, where panels are automatically created and deleted. For example, if you only have one panel, and you press `Alt+.`, a new panel should be created automatically. Then, when you close all tabs in a panel, it automatically gets deleted.

**Comment by mbnuqw** [comment] 2023-06-11 17:26
Duplicate of #534 and #265 - all planned after v5 release.

**Closed as completed by mbnuqw** 2023-06-11 17:26 UTC
Labels: type: duplicate
