### ISSUE TITLE
'Container of new tab' option for panel does not open new tabs in the chosen container

### ISSUE THREAD

**Issue by Makeshift** [mbnuqw/sidebery#1219] opened 2023-09-09 13:29 UTC
## Steps to reproduce
- Configure a Sidebery panel to open new tabs in a specific container, like so:
![image](https://github.com/mbnuqw/sidebery/assets/345013/f0d484dd-d6ad-4474-a016-8bc1afa5b4b0)
- Activate/select that panel in Sidebery
- Open a completely fresh tab by clicking the + at the top of Firefox, or Ctrl+T

## Expected behavior
With these settings, new tabs with that panel selected should open in the chosen container.

## Actual behavior
New tabs are not opened in any container.

(Note: 'Reopen tab that was dropped...' works fine, and child pages opened within a container also work fine)

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
{
  "settings": {
    "version": "4.10.2",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "reinit",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "/AWS.*/",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "prev_act",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "einstein",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "169.9 kb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "3.4 kb",
      "expandedBookmarks": "67 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "10.5 kb",
      "favicons": "146.5 kb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.1 kb",
      "prevTabsData_v4": "1.1 kb",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "snapshots_v4": "2 b",
      "tabsData_v4": "3 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "5ySdvHl8Vq25",
      "name": 4,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-6",
      "dropTabCtx": "firefox-container-6",
      "moveTabCtx": "firefox-container-6",
      "moveTabCtxNoChild": false,
      "urlRulesActive": false,
      "urlRules": 28
    },
    {
      "type": "tabs",
      "id": "oMsLb9JUHpZ5",
      "name": 18,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-6",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": "direct",
      "includeHostsActive": true,
      "includeHosts": 28,
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-12",
      "name": 58,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-13",
      "name": 60,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-14",
      "name": 46,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-15",
      "name": 70,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-16",
      "name": 63,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-17",
      "name": 61,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-18",
      "name": 74,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-19",
      "name": 71,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-20",
      "name": 59,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-21",
      "name": 57,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 23
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 286,
    "foldersCount": 35,
    "separatorsCount": 0,
    "maxDepth": 4
  }
}
```
</details>

<details>
<summary><b>Logs</b></summary>
No logs are produced in Sidebery's devtools console when a new tab is opened.
</details>

**Comment by mbnuqw** [comment] 2023-09-10 07:34
Duplicate of https://github.com/mbnuqw/sidebery/issues/305

**Closed as completed by mbnuqw** 2023-09-10 07:34 UTC
Labels: type: duplicate
