### ISSUE TITLE
[v5] Tree forgotten on restart

### ISSUE THREAD

**Issue by michalfita** [mbnuqw/sidebery#861] opened 2022-11-25 11:11 UTC
## Steps to reproduce
- I still struggle with #798, moreover sometime restart doesn't help and tabs don't load
- Close Sideberry in both windows
- Wait couple minutes
- Turn Sideberry again in one window, but clicking the icon on the bar
- If you're lucky tabs will appear
- But in such case the tree structure is gone (I never had such trouble with Tree Style Tabs).

## Expected behavior
- Open all tabs with tree structure retained

## Actual behavior
- All tabs appear flat, structure is lost

## Debug info

<details><summary><b>Addon data</b></summary><code>
{
  "addonVersion": "5.0.0b29",
  "firefoxVersion": "107.0",
  "settings": {
    "nativeScrollbars": false,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": false,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "s",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "density": "default",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "clipboardWrite": false,
    "webRequest": false,
    "webRequestBlocking": false
  },
  "storage": {
    "size": "491 kb",
    "props": {
      "containers": "969 b",
      "favDomains": "55.9 kb",
      "favHashes": "3.82 kb",
      "favicons": "265 kb",
      "prevTabsDataCache": "51.3 kb",
      "profileID": "14 b",
      "settings": "3.61 kb",
      "sidebar": "415 b",
      "tabsDataCache": "110 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "tabs-panel": {
        "type": 2,
        "id": "tabs-panel",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": false,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      }
    },
    "nav": [
      "tabs-panel",
      "search",
      "add_tp",
      "sp-0",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "purple",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 611
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 456
    }
  ],
  "bookmarks": "TypeError: browser.bookmarks is undefined"
}
</code></details>

<details><summary><b>Logs</b></summary><code>
<!-- To get logs: 
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.connectTo: No confirmation: bg [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.connectTo: No confirmation: bg [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.connectTo: No confirmation: bg [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: No confirmation: bg cacheTabsData [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Target port has an error:
 
Object { message: "No confirmation" }
[chunk-PXMRWLXI.js:1426:13](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:1] IPC.request: Cannot find appropriate port, trying to reconnect... [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
[sidebar:9] Tabs loading: Cannot find panels: -1 [chunk-PXMRWLXI.js:1420:11](moz-extension://7d6f434c-a942-417e-a399-b0891b8be111/chunk-PXMRWLXI.js)
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!
</code></details>

**Comment by megamorphg** [comment] 2022-11-27 04:35
My tabs also get flat... but only in one window.
I then have to restore that window from a snapshot.

Does #864 also happen for you @michalfita ?

**Comment by michalfita** [comment] 2022-11-27 07:26
More #798 than #864, but symptoms are almost identical, no tabs load after FF restarts. Interestingly this problem doesn't exist in v4 (I have it on another PC).

**Comment by mbnuqw** [comment] 2023-01-26 18:35
Should be fixed in v5.0.0b30. Please reopen if the issue is still present.

**Closed as completed by mbnuqw** 2023-01-26 18:35 UTC
Labels: type: bug, reproduced: yes

**Comment by nowayhaze** [comment] 2024-01-02 05:44
A variant of this issue still happens for 5.0.0.1 on Firefox 121 with Windows 10. Specifically, if I have Sidebery already open after a restart, the tree collapses after attempting to restore tabs. 

However, I have a weird workaround: if I hide Sidebery _first_ after a restart then restore tabs, Sidebery automatically opens and the tabs will be restored with the proper structure. 
EDIT: This workaround does not work when there are pinned tabs.
