### ISSUE TITLE
Pin/Stick/Save Snapshots

### ISSUE THREAD

**Issue by FabianoLothor** [mbnuqw/sidebery#964] opened 2023-02-26 23:23 UTC
## Description

Please, add an option to pin a snapshot, when pinned, the rules to auto delete the snapshots aren't applied to those pinned.

**Comment by mbnuqw** [comment] 2024-03-24 08:25
Related: #161

**Comment by mbnuqw** [comment] 2024-03-24 08:27
Duplicate of #456

**Closed as completed by mbnuqw** 2024-03-24 08:27 UTC
Labels: type: duplicate
