### ISSUE TITLE
New tabs aren't opened in assigned container

### ISSUE THREAD

**Issue by adam-fox** [mbnuqw/sidebery#931] opened 2023-02-07 16:42 UTC
## Steps to reproduce
- In the panels settings set "Container of new tab" to open in a container
- Cmd+T 

## Expected behavior
- New tab opens in container assigned to to panel

## Actual behavior
- New tab opens in unassigned container within panel.

## Debug info

<details><summary><b>Addon data</b></summary><code>

</code></details>

<details><summary><b>Logs</b></summary><code>

</code></details>

**Comment by milescowan** [comment] 2023-02-09 12:43
I am experiencing the same plus what may be a related issue: links clicked in other programs open in an unassigned container in a panel that specifies a container for new tabs. Middle clicking in the panel correctly opens a new tab in the assigned container.

Links from other applications were working correctly a few versions ago. I'm not sure if ctrl-T worked previously because I never use it.

**Comment by mbnuqw** [comment] 2023-02-11 19:38
Duplicate of #305, planned to be fixed soon (beta32-33)

**Closed as completed by mbnuqw** 2023-02-11 19:38 UTC
Labels: type: duplicate
