### ISSUE TITLE
No context menu?

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#41] opened 2019-04-17 18:06 UTC
I'm using v2.4.1, Firefox 66.0.3 and Arch Linux. When I right-click on a tab, I don't get a context menu. The context menu used to work on v2.4.0.

**Comment by mbaz** [comment] 2019-04-17 18:10
The problem was that the conext menu options list was empty (I never disabled any context menu options; maybe this was triggered by a version update?). After selecting a few options, the context menu appears as it should.

**Comment by mbnuqw** [comment] 2019-04-17 18:18
Thank you for reporting anyway. I'll check this out.

**Comment by mbaz** [comment] 2019-04-19 13:52
I can confirm that after a Firefox restart, I lost the context menu configuration and the tabs theme. This last one is especially painful, since I had spent some time getting the colors just right.

**Comment by mbnuqw** [comment] 2019-04-19 13:58
ouch.. sorry
Could you go to settings and check size of cached favicons?

**Comment by mbaz** [comment] 2019-04-19 14:20
![VoxtbhK](https://user-images.githubusercontent.com/1630034/56428248-3c7a7280-62ae-11e9-9788-23064572a37f.png)

**Comment by mbnuqw** [comment] 2019-04-19 14:22
Thanks
Looks like problem with storage... I'll try to fix this asap

**Comment by mbaz** [comment] 2019-04-30 14:36
This may be related to the same issue: today I had to reboot my computer without a clean shutdown. After restarting Firefox, I lost my tab groups. The tabs are still there, and the tab used to group the tabs is there, but it's empty. If that doesn't make sense, let me know, it's a bit hard to explain :)

**Comment by mbnuqw** [comment] 2019-04-30 15:20
Few questions:
1. Did you mean the group page is empty? like that:
![screenshot-2019 04 30-20 04 11_001](https://user-images.githubusercontent.com/6276694/56971824-602d9a80-6b83-11e9-9014-ebb9f80379d7.png)

2. And child tabs are nested? like that:
![screenshot-2019 04 30-20 04 19_001](https://user-images.githubusercontent.com/6276694/56971953-99660a80-6b83-11e9-9d7c-b17cd3416db2.png)

3. And even after reloading of group page issue is still there?
4. Does the URL of the group page end with something like "::id::fZVEzDm3C6jG"

**Comment by mbaz** [comment] 2019-04-30 15:26
1. Yes, the group page is empty, but it still had the correct name.
2. The child tabs are not nested; they're at the same level as the group page.
3. I didn't try that -- I'll try to reproduce the issue and report back.
4. Yes.

**Comment by mbnuqw** [comment] 2019-04-30 15:31
Thanks, there is no need to reproduce this, I think, it's just failed restoring tree algorithm.

**Comment by mbaz** [comment] 2019-04-30 15:50
Alright -- let me know if you need more info or if you want me to test something.

**Comment by mbnuqw** [comment] 2019-09-07 17:45
Since I rewrote all mentioned here modules (context-menu, tree-restoring), closing it.

**Closed by mbnuqw** 2019-09-07 17:45 UTC
Labels: bug
