### ISSUE TITLE
A few questions about Pinned tabs

### ISSUE THREAD

**Issue by i110077** [mbnuqw/sidebery#1004] opened 2023-03-28 11:24 UTC
Test environment: Windows10 - Firefox 111.0.1

1. I put a few pinned tabs at the top, but every time I restart the browser, there are several pinned tabs that will always be reopened automatically. When I close the browser, they are all uninstalled. I can’t find the relevant information. Setting options, is this a bug?

2. After closing the pinned tabs page, it will disappear directly from the fixed tab panel. Can you keep the fixed tab there like ACE? Whether it is closed or uninstalled

3. I opened multiple windows today, and after restarting the browser, all the pinned tabs disappeared, and there is no way to get them back. This should be a bug, right?

4. In addition, can the pinned tabs be always fixed in the new window and private window? Currently, there is no pinned tabs in the new window

**Comment by mbnuqw** [comment] 2024-03-25 08:54
1. By default, Firefox loads pinned tabs on start, so I don't see any issue here and Sidebery doesn't control this behavior.
2. Unload it instead of closing.
3. Right, but I can't reproduce it.
4. If you mean showing same pinned tabs across different windows, track #1290

**Closed as completed by mbnuqw** 2024-03-25 08:54 UTC
