### ISSUE TITLE
In about:config, when browser.tabs.closeWindowWithLastTab is false, after closing last tab, have to reload Sidebery for it to show any tabs

### ISSUE THREAD

**Issue by alurm** [mbnuqw/sidebery#1417] opened 2024-01-16 19:16 UTC
Hi! Love the extension.

In about:config, when browser.tabs.closeWindowWithLastTab is false, after closing last tab, have to reload Sidebery for it to show any tabs.

## Steps to reproduce

- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Open about:config
- Set browser.tabs.closeWindowWithLastTab to false
- Close all tabs
- Do work (open and close tabs)

## Expected behavior

Sidebery works as usual.

## Actual behavior

Sidebery shows no tabs until reopened.

![image](https://github.com/mbnuqw/sidebery/assets/108410815/3c736aef-d1fe-4213-8f1c-f818dd55f404)

## Debug info

Mozilla Firefox 121.0.1, Void Linux, X11

**Comment by alurm** [comment] 2024-01-16 20:53
Duplicate of https://github.com/mbnuqw/sidebery/issues/1230

**Comment by mbnuqw** [comment] 2024-03-13 09:10
Duplicate of #1307, which is a duplicate of #1230

**Closed as completed by mbnuqw** 2024-03-13 09:10 UTC
Labels: type: duplicate
