### ISSUE TITLE
Sync option for panel configuration

### ISSUE THREAD

**Issue by OJFord** [mbnuqw/sidebery#259] opened 2020-06-02 14:24 UTC
## Description
I'd like to keep panel configuration in sync across devices (or rather FF installs) but presently it's not included in the sync data.

i.e. containers, new tab / URL matching settings, and  any pinned tabs.

**Comment by mbnuqw** [comment] 2020-06-03 10:32
Duplicate of #54 (hm... I think I need to update title of that issue)

**Closed by mbnuqw** 2020-06-03 10:32 UTC

**Comment by OJFord** [comment] 2020-06-03 12:34
Ah, sorry.
