### ISSUE TITLE
Feature Request: Hide Tab for [X] seconds instead of immediately closing (huge time saver)

### ISSUE THREAD

**Issue by HenryTheVacuum** [mbnuqw/sidebery#1074] opened 2023-06-14 14:20 UTC
Hiding tabs (for [X] seconds) instead of closing them would offer substantial time savings and enhance user experience compared to closing them outright. The problem being, if you accidentally close a tab or multiple, re-opening them requires a full page reload. If they were just hidden temporarily instead, it would provide a much snappier user experience with minimal overhead.

**Comment by emvaized** [comment] 2023-06-25 04:26
I belive this is something you should better request at Mozilla to be included in the Firefox itself — so that, when the tab gets restored (for example by Ctrl+Shift+T hotkey, or by extension via API), it gets loaded from cache rather than cold reloaded; with cached version created automatically each time when the tab is requested to get closed. 

But I don't really think they will include this, as it seems like quite a lot of work for something so small and unnoticable by most users — after all, you're not supposed to close tabs accidentally _that_ often to consider this such a huge time saver... 

The proposed solution with tabs hiding by this extension is quite shaky in my opinion, both from UX and confidentiality standpoints — I can immediately think of multiple examples when temporarly hiding tabs instead of closing (with user probably unaware of this behavior) could lead to bad user experience. Not to mention you also have to handle situations when, for example, browser was crashed or closed during these [X] seconds, so the "closed" tabs never get actually closed.

**Comment by mbnuqw** [comment] 2024-03-25 11:48
Duplicate of #999

**Closed as completed by mbnuqw** 2024-03-25 11:48 UTC
Labels: type: duplicate
