### ISSUE TITLE
Snapshots Inaccessible

### ISSUE THREAD

**Issue by talismanick** [mbnuqw/sidebery#834] opened 2022-11-03 20:46 UTC
I persist all my tabs (because Auto Tab Discard means I only use a few Gb of memory at any given moment, for recently-used tabs), and categorize them with Sidebery. I'd estimate I've accumulated ~800, because they accrete across restarts with "remember history" and "startup > open previous tabs and windows" 

My browser crashed, so, per the usual, I restarted. This time, however, it loads a window with a blank tab (known to happen) and crashes on restoring from "History > Recently Closed Windows" (new). The window freezes, then disappears, when I'd normally have both the dummy empty-tab window and the window with all my tabs. 

Sidebery used to consistently snapshot automatically (I checked a few weeks ago), but now it's refusing to help recover the most recent snapshot:

![image](https://user-images.githubusercontent.com/55632194/199827911-d8ae11c2-6375-43b2-8fa5-b119ed26d06f.png)

The main menu says there's still 126MB of data under "snapshots_v4". Is there any way I could access this and recover my tabs? 

Apologies if this has been submitted before: I didn't see anything like it among the 100+ issues mentioning "snapshots". (the ones I opened and read completely, at any rate)

**Comment by mbnuqw** [comment] 2022-11-04 11:45
Check the https://github.com/mbnuqw/sidebery/issues/595. To prevent this issue in the future (or increase overall performance) set more strict limits for auto snapshots.

Closing as a duplicate of #595

**Closed as completed by mbnuqw** 2022-11-04 11:45 UTC
Labels: type: duplicate
