### ISSUE TITLE
Can no longer snapshot, export or even delete a snapshot storage

### ISSUE THREAD

**Issue by rjameson3** [mbnuqw/sidebery#595] opened 2022-04-01 14:21 UTC
Not sure how to fix - but I can no longer snapshot, nor see any, cannot export - it does not popup where to save, cannot delete the snapshot storage in hopes to clear the problem.     Any ideas why suddenly it is breaking down?     Tried to reload, reboot to no avail.   This is the latest firefox, on macOS.

**Comment by mbnuqw** [comment] 2022-04-02 17:43
Thanks for the report! Could you open DevTools for sidebery (open this url in new tab: about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension), then navigate to "console" tab and check if there is any error message (you may need to repeat the actions - create/delete snapshot, export, etc..)?

**Comment by rjameson3** [comment] 2022-04-02 17:58
I ran the above and there are errors - VueJS.  I included a PDF screenshot
[2022-04-02_12-54-53.pdf](https://github.com/mbnuqw/sidebery/files/8403116/2022-04-02_12-54-53.pdf)
.

**Comment by mbnuqw** [comment] 2022-04-02 18:42
Thank you. Now, let's try to save snapshots as a backup and clear them in sidebery's storage and check if the problem is still there.

To backup snapshots run `await browser.storage.local.get('snapshots_v4')` in console, then right click on the next (output) line and click on the "Copy object". Then paste it in any text editor and save as file.

To clear snapshots run `await browser.storage.local.set({ snapshots_v4: [] })`, then reload settings page. Check if the problem still exists.

To restore snapshots from backup type `await browser.storage.local.set()`, then copy-paste all content of the backup between brackets and run.

**Comment by rjameson3** [comment] 2022-04-02 18:53
In both of the first two above commands, the next line produced an error:
Uncaught (in promise) Error: An unexpected error occurred

When I copied the object - it was only {}
<img width="546" alt="image" src="https://user-images.githubusercontent.com/14798911/161397284-66fdc53e-1c84-4c24-be59-f48db24b567f.png">

**Comment by mbnuqw** [comment] 2022-04-02 19:19
Ok, looks like calling the storage API leading to that unexpected error (maybe because of large size of data).

Can you try to run this `await browser.storage.local.get('favAutoCleanTime')` and this `await browser.storage.local.get('favicons')` to check if it work ok with different fields?

Then try to completely remove snapshots field with `await browser.storage.local.remove('snapshots_v4')` and reload addon

**Comment by rjameson3** [comment] 2022-04-02 19:25
Here are the results:  The last failed.

<img width="2253" alt="image" src="https://user-images.githubusercontent.com/14798911/161398158-8cfc3350-f76a-4e2c-99ef-34b03782367d.png">

**Comment by mbnuqw** [comment] 2022-04-03 18:16
I can reproduce this issue now (partially). The cause of this can be the big size of the stored value or some damage in db.

To recover normal functionality:
#### Backup addon data without snapshots
1. Run in console `await browser.storage.local.get(['settings', 'panels_v4', 'tabsData_v4', 'prevTabsData_v4', 'profileID', 'favicons', 'favUrls'])` and save result

#### Remove addon DB
2. Open `about:support`
3. Open "Profile Directory"
4. Find the id of addon: run in console `await browser.runtime.getURL('')`. The result will be in "moz-extension://ADDON_ID/" form
5. Close Firefox
6. Open `{Profile Directory}/storage/default/moz-extension+++{ADDON_ID}^userContextId=.../idb`
7. Remove content of the "idb" directory.

#### Restore addon data
8. Open firefox
9. Open DevTools `about:devtools-toolbox?id=%7B3c078156-979c-498b-8990-85f7987dd929%7D&type=extension`
10. Run `await browser.storage.local.set( copy-pasted text from backup )`

**Comment by rjameson3** [comment] 2022-04-03 19:39
When I run the backup addon command and save result, am I to right click/save object to a text file which produces a rather long bunch of data between {  }  - then copy all that text inbetween  the (  ) at the restore at the end?

**Comment by rjameson3** [comment] 2022-04-03 19:57
I backed up the idb folder just in case, performed the above  - but all the tabs ended up in the default panel and my other half dozen panels were empty.

**Comment by rjameson3** [comment] 2022-04-03 20:15
WooHoo - success....I hope.   :)    I ran the command the first time, it put all tabs in the default panel, on a hunch (after looking at all the data in the backup, I see that each tab was assigned a panel ID so it should have placed them)....I re-ran the same command again and this time after quitting firefox-reopen - tabs were in proper panel.  WHEW!!!!   Was able to create a snapshot and export data.   Looks like from what I see now - I am back in business.   Thank you!!!!!    Your add-on is a tool I cannot live without.

With all this, do you think this was just corruption or is there a size limit that I ran into ?

**Closed** 2024-03-08 05:02 UTC
Labels: type: bug, status: resolved in beta, reproduced: yes
