### ISSUE TITLE
New tab doesn't have a container (sometimes)

### ISSUE THREAD

**Issue by pointlessone** [mbnuqw/sidebery#713] opened 2022-08-02 10:21 UTC
## Steps to reproduce

Set up a panel with a Container for new tab. Open a new tab (using Cmd-T or + button in the Tab Bar).

**Note**: Opening a new tab from the panel (e.g. double-clicking the panel) opens new tab in the designated container.

## Expected behavior

New tab is opened in the container set for new tabs.

## Actual behavior

New tab is opened without a container attached.

### Addon data
<details><code>
{
  "settings": {
    "version": "4.10.1",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "session",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 3,
    "snapIntervalUnit": "hr",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": true,
    "actualAllUrls": false,
    "actualTabHide": true
  },
  "storage": {
    "size": "2.4 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "5.1 kb",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "26.5 kb",
      "favicons": "1.2 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.1 kb",
      "prevTabsData_v4": "152.5 kb",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "snapshots_v4": "861 kb",
      "tabsData_v4": "151.9 kb",
      "tabsMenu": "308 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "CipBRL8DBJvD",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": 40,
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "firefox-container-34",
      "dropTabCtx": "firefox-container-34",
      "moveTabCtx": "firefox-container-34",
      "moveTabCtxNoChild": false,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Bq-_UYe91kZD",
      "name": 6,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-8",
      "name": 5,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-11",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-15",
      "name": 10,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-21",
      "name": 10,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-22",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-23",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-24",
      "name": 10,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-25",
      "name": 3,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-30",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-31",
      "name": 12,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-33",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-34",
      "name": 6,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-35",
      "name": 12,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-36",
      "name": 14,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-37",
      "name": 10,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-38",
      "name": 17,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-39",
      "name": 13,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 228
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1380
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 83
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 1
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 1346
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 2319
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 230
    }
  ],
  "tabsMenu": [
    [
      "undoRmTab",
      "mute",
      "reload",
      "bookmark"
    ],
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    "close"
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 5869,
    "foldersCount": 165,
    "separatorsCount": 6,
    "maxDepth": 5
  }
}
</code></details>

### Logs
<details>

There's no option to enable logs:
![Screen Shot 2022-08-02 at 12 56 30](https://user-images.githubusercontent.com/7405/182347403-58543425-b6b3-4ed0-89b8-70349624240c.png)

No logs otherwise.

</details>

**Comment by mbnuqw** [comment] 2022-08-18 15:23
Duplicate of #305
(Planned to be fixed in v5)

**Closed by mbnuqw** 2022-08-18 15:23 UTC
