### ISSUE TITLE
Ability to Rename a tab

### ISSUE THREAD

**Issue by smokelore** [mbnuqw/sidebery#282] opened 2020-07-17 20:42 UTC
Hey y'all. I had a few shipment tracking tabs open and pinned, and I realized it would be nice to be able to rename each tab so I could remember which shipment was which. I imagine this feature would be useful for other purposes. Thought I'd put it out there and see if anyone else agreed.

This is my favorite tab manager by far. Appreciate all the work you're doing. Cheers.

**Comment by mbazdell** [comment] 2020-07-31 01:51
I'm currently using Tab ReTitle to achieve this but it's janky at best. I would appreciate this feature very much being built in.

**Comment by SeerLite** [comment] 2021-02-14 02:57
Duplicate of #185

**Closed** 2024-03-09 12:56 UTC
