### ISSUE TITLE
Can the data that can be synchronized through firefox be added with the data of "container settings"?

### ISSUE THREAD

**Issue by Felmon** [mbnuqw/sidebery#1091] opened 2023-07-03 07:49 UTC
## Description
Can the data that can be synchronized through firefox be added with the data of "container settings"? I found that it was inconsistent with the exported data. When changing the computer, when synchronizing the data, it needs to be exported and then imported to the new device. It would be nice if all could be synchronized through firefox

**Comment by mbnuqw** [comment] 2024-03-25 15:44
Duplicate of #54

**Closed as completed by mbnuqw** 2024-03-25 15:44 UTC
Labels: type: duplicate
