### ISSUE TITLE
Sorting tabs

### ISSUE THREAD

**Issue by alexander-paterson** [mbnuqw/sidebery#945] opened 2023-02-16 19:09 UTC
I use FoxyTab to sort my tabs. 

When I have tabs open on multiple panels and sort the tabs, all the tabs get pulled into one panel.

I'd love to have a keyboard shortcut to allow me to sort tabs by url or domain but keep them in the panels they are already in.

**Comment by mbnuqw** [comment] 2023-02-18 07:26
Duplicate of #643

**Closed as completed by mbnuqw** 2023-02-18 07:26 UTC
Labels: type: duplicate
