### ISSUE TITLE
Left click on Panel: do NOT create a new tab - I cannot disable this currently

### ISSUE THREAD

**Issue by JohnVKRDam** [mbnuqw/sidebery#387] opened 2021-05-08 09:01 UTC
## Description
PLEASE add an option to disable the 'feature' of adding a new tab when I click the panel.

I cannot disable this.

The option SETTINGS > Mouse > "left click on tabs panel" is already set to NONE. It does nothing, though. But, I'm guessing this option is not actually for clicking the panel in the left panel pane, but for the background of the tabs list, right?

Anyway, it is INCREDIBLY annoying when I click on a panel in the left panel menu, a new tab is added, even if I don't want it do that at all.

The option of adding a new tab by double clicking the background of the tabs list and the middle-mouse button on the background of the tabs list is plenty options to do that already. I really, really don't need it to do that from left-clicking the panel itself as well. Single left-clicking is for SELECTING, not for CREATING.

**Comment by buffum** [comment] 2021-05-24 18:28
I also would like to be able to disable this behavior, please...

**Comment by mbnuqw** [comment] 2021-05-27 17:52
Duplicate of #363

**Closed by mbnuqw** 2021-05-27 17:52 UTC
