### ISSUE TITLE
Sideberry on multiple windows

### ISSUE THREAD

**Issue by Dajova** [mbnuqw/sidebery#909] opened 2023-01-20 13:03 UTC
## Steps to reproduce
- Open multiple windows on multiple monitors (one window per monitor).
- Rebooting or just restart Firefox while the side panels are closed on all windows except one

## Expected behavior
- Should not open with Sideberry automatically on windows it was closed on.

## Actual behavior
- Majority of previous windows opens up with Sideberry automatically. In fact, clicking on the Sideberry opens it up again, indicating it wasnt actually open, but it was. Hence it only closes after 2 clicks.

**Comment by mbnuqw** [comment] 2023-01-20 19:18
Can't reproduce, please, provide sidebery debug info and more verbose steps to reproduce.

**Comment by Dajova** [comment] 2023-01-20 19:41
Updated main post about a step that i was explaining about in the behaviour sections, should be more understandable now. Also, here's the debug: https://gist.github.com/Dajova/362d90ee11a690cf373744ba3c0a6e9a

**Comment by mbnuqw** [comment] 2023-01-21 06:46
I fixed a 2-click issue, so it will shipped in the next beta. Speaking of sidebar state on window opening - it's not possible for addons to control this behavior, so it's up to Firefox. Addons can only open/close sidebar on a direct [user-click](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).

**Comment by mbnuqw** [comment] 2023-09-29 12:32
Resolved in v5.0.0

**Closed as completed by mbnuqw** 2023-09-29 12:32 UTC
Labels: type: bug, reproduced: yes
