### ISSUE TITLE
2 Pane Bookmarks

### ISSUE THREAD

**Issue by IntGen1** [mbnuqw/sidebery#334] opened 2021-01-02 12:45 UTC
Hello!
Can you add "2 Pane Bookmarks" feature to bookmark panel like in old Opera or FireFox
https://piro.sakura.ne.jp/xul/_bookmarks2pane.html.en
This provides separated "Bookmarks" Sidebar panel like Opera. This splits the Bookmarks Sidebar panel with 2 panes. When you choose a folder from the above tree, the contents will be shown in the below pane
![Capture](https://user-images.githubusercontent.com/76870602/103457501-047cc280-4d11-11eb-8cf6-17b3c1da9cae.PNG)
I can't live without that extention.
Thank you!

**Comment by mbnuqw** [comment] 2024-03-10 08:46
Duplicate of #294 and #554

**Closed by mbnuqw** 2024-03-10 08:46 UTC
