### ISSUE TITLE
Feature Request: Static titles for pinned tabs

### ISSUE THREAD

**Issue by mbrasch** [mbnuqw/sidebery#237] opened 2020-05-12 09:58 UTC
I use many pinned tabs at work (around 40) and it would very helpful to give them fixed names. That would make it easier to identify them. Particularly when they show something like "Login in" or "loading error" (when outside of our internal network).

**Comment by mbnuqw** [comment] 2020-05-23 20:13
Duplicate of #185

**Closed by mbnuqw** 2020-05-23 20:13 UTC
