### ISSUE TITLE
Tabs and panel behaviour different across windows

### ISSUE THREAD

**Issue by arcxne** [mbnuqw/sidebery#1422] opened 2024-01-21 08:41 UTC
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Create 2 panels and open tabs are inside them
- Hide 1 panel
- Open a new window

## Expected behavior
- Hidden panel stays hidden, other panel is visible
- Tabs in first window are shown in new window

## Actual behavior
- Both panels are open
- There are no tabs from first window in the new window

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```json
{
  "addonVersion": "5.0.0",
  "firefoxVersion": "122.0",
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": true,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": false,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "vertical",
    "navBarInline": false,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": false,
    "hideDiscardedTabPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "subPanelRecentlyClosedBar": true,
    "subPanelBookmarks": true,
    "subPanelHistory": true,
    "groupLayout": "list",
    "containersSortByName": false,
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "dndActTabFromLink": true,
    "dndActSearchTab": true,
    "dndMoveTabs": false,
    "dndMoveBookmarks": false,
    "searchBarMode": "dynamic",
    "searchPanelSwitch": "same_type",
    "searchBookmarksShortcut": "",
    "searchHistoryShortcut": "",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "activateLastTabOnPanelSwitchingLoadedOnly": true,
    "switchPanelAfterSwitchingTab": "always",
    "tabRmBtn": "hover",
    "activateAfterClosing": "prev_act",
    "activateAfterClosingStayInPanel": true,
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "tabsUnreadMark": false,
    "tabsUpdateMark": "none",
    "tabsUpdateMarkFirst": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": true,
    "tabsPanelSwitchActMoveAuto": true,
    "tabsUrlInTooltip": "full",
    "newTabCtxReopen": false,
    "tabWarmupOnHover": true,
    "tabSwitchDelay": 0,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "pinnedNoUnload": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "autoExpandTabsOnNew": false,
    "rmChildTabs": "folded",
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 2,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "ignoreFoldedParent": true,
    "colorizeTabs": false,
    "colorizeTabsSrc": "container",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "inheritCustomColor": false,
    "hideInact": true,
    "hideFoldedTabs": true,
    "hideFoldedParent": "none",
    "nativeHighlight": false,
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "oldBookmarksAfterSave": "ask",
    "loadHistoryOnDemand": true,
    "fontSize": "m",
    "animations": true,
    "animationSpeed": "fast",
    "theme": "plain",
    "density": "loose",
    "colorScheme": "ff",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": true,
    "snapInterval": 1,
    "snapIntervalUnit": "day",
    "snapLimit": 5,
    "snapLimitUnit": "snap",
    "snapAutoExport": true,
    "snapAutoExportType": "md",
    "snapAutoExportPath": "Sidebery/snapshot-%Y.%M.%D-%h.%m.%s",
    "snapMdFullTree": true,
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 0,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "tabsSecondClickActPrevPanelOnly": true,
    "shiftSelAct": true,
    "activateOnMouseUp": true,
    "tabLongLeftClick": "edit_title",
    "tabLongRightClick": "none",
    "tabMiddleClick": "close",
    "tabMiddleClickCtrl": "discard",
    "tabMiddleClickShift": "duplicate",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickRemove": false,
    "bookmarksMidClickPos": "default",
    "historyLeftClickAction": "open_in_act",
    "historyLeftClickActivate": false,
    "historyLeftClickPos": "default",
    "historyMidClickAction": "open_in_new",
    "historyMidClickActivate": false,
    "historyMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false,
    "selectActiveTabFirst": true
  },
  "permissions": {
    "allUrls": false,
    "webRequest": false,
    "webRequestBlocking": false,
    "proxy": false,
    "tabHide": true,
    "clipboardWrite": false,
    "history": true,
    "bookmarks": true,
    "downloads": true
  },
  "storage": {
    "size": "560 kb",
    "props": {
      "containers": "1.07 kb",
      "expandedBookmarkFolders": "215 b",
      "favDomains": "17.2 kb",
      "favHashes": "4.22 kb",
      "favicons_01": "363 kb",
      "favicons_02": "2 b",
      "favicons_03": "2 b",
      "favicons_04": "2 b",
      "favicons_05": "2 b",
      "lastSnapTime": "13 b",
      "profileID": "14 b",
      "settings": "4.81 kb",
      "sidebar": "11.7 kb",
      "sidebarCSS": "1.89 kb",
      "snapshots": "122 kb",
      "tabsDataCache": "32.5 kb",
      "ver": "7 b"
    }
  },
  "sidebar": {
    "nav": [
      "Sb_yHksKat9h",
      "Nf987GgArhor",
      "D_bQipsnQ-hn",
      "iCXeWCEXdSmI",
      "auiW6_Pldv9h",
      "krQ3pcm36WHK",
      "8W4xYMO_odtI",
      "xUKv1hk0WQjK",
      "GBYLB1-DvBtD",
      "nntpCxURcMKf",
      "cjHHlXF_l58h",
      "lnZJh5q5moEI",
      "BVBuMQtYZaVz",
      "Oh6c7CKh96Uz",
      "DXfa1Sha026h",
      "EJfbw4CRE71j",
      "GeJE3DzD6c-j",
      "tcP_bdcKvUYj",
      "ixO3f04oU8eL",
      "PPGZCC9fzpEx",
      "RagTGKgFgnhD",
      "UbKS62tIsvhM",
      "PdYSwdaKczPD",
      "s0-kYm-cXVaK",
      "0BJcTueRXGUR",
      "pmsA015tCUeD",
      "ahi5ZhcEpF2H",
      "add_tp",
      "create_snapshot",
      "sp-0",
      "settings"
    ],
    "panels": {
      "Sb_yHksKat9h": {
        "type": 2,
        "id": "Sb_yHksKat9h",
        "name": "len: 8",
        "color": "red",
        "iconSVG": "icon_code",
        "iconIMGSrc": "len: 1",
        "iconIMG": "len: 686",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "Nf987GgArhor": {
        "type": 2,
        "id": "Nf987GgArhor",
        "name": "len: 3",
        "color": "red",
        "iconSVG": "icon_book",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "D_bQipsnQ-hn": {
        "type": 2,
        "id": "D_bQipsnQ-hn",
        "name": "len: 3",
        "color": "red",
        "iconSVG": "icon_gamepad",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "iCXeWCEXdSmI": {
        "type": 2,
        "id": "iCXeWCEXdSmI",
        "name": "len: 9",
        "color": "red",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "auiW6_Pldv9h": {
        "type": 2,
        "id": "auiW6_Pldv9h",
        "name": "len: 9",
        "color": "yellow",
        "iconSVG": "icon_book",
        "iconIMGSrc": "len: 1",
        "iconIMG": "len: 290",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "krQ3pcm36WHK": {
        "type": 2,
        "id": "krQ3pcm36WHK",
        "name": "len: 7",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "8W4xYMO_odtI": {
        "type": 2,
        "id": "8W4xYMO_odtI",
        "name": "len: 7",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "xUKv1hk0WQjK": {
        "type": 2,
        "id": "xUKv1hk0WQjK",
        "name": "len: 7",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "GBYLB1-DvBtD": {
        "type": 2,
        "id": "GBYLB1-DvBtD",
        "name": "len: 4",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "nntpCxURcMKf": {
        "type": 2,
        "id": "nntpCxURcMKf",
        "name": "len: 9",
        "color": "yellow",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "cjHHlXF_l58h": {
        "type": 2,
        "id": "cjHHlXF_l58h",
        "name": "len: 8",
        "color": "green",
        "iconSVG": "icon_mail",
        "iconIMGSrc": "len: 1",
        "iconIMG": "len: 850",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "lnZJh5q5moEI": {
        "type": 2,
        "id": "lnZJh5q5moEI",
        "name": "len: 4",
        "color": "green",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "BVBuMQtYZaVz": {
        "type": 2,
        "id": "BVBuMQtYZaVz",
        "name": "len: 6",
        "color": "green",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "Oh6c7CKh96Uz": {
        "type": 2,
        "id": "Oh6c7CKh96Uz",
        "name": "len: 4",
        "color": "green",
        "iconSVG": "icon_clipboard",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "DXfa1Sha026h": {
        "type": 2,
        "id": "DXfa1Sha026h",
        "name": "len: 7",
        "color": "blue",
        "iconSVG": "icon_play",
        "iconIMGSrc": "len: 1",
        "iconIMG": "len: 746",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "EJfbw4CRE71j": {
        "type": 2,
        "id": "EJfbw4CRE71j",
        "name": "len: 6",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "GeJE3DzD6c-j": {
        "type": 2,
        "id": "GeJE3DzD6c-j",
        "name": "len: 11",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [
          {
            "id": "uPzzTUjFjL6J",
            "active": true,
            "url": "moz-extension://de42946f-f76b-4929-8175-712d928d0804/",
            "name": "Sidebery page",
            "topLvlOnly": false
          }
        ],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "tcP_bdcKvUYj": {
        "type": 2,
        "id": "tcP_bdcKvUYj",
        "name": "len: 8",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "PPGZCC9fzpEx": {
        "type": 2,
        "id": "PPGZCC9fzpEx",
        "name": "len: 5",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "RagTGKgFgnhD": {
        "type": 2,
        "id": "RagTGKgFgnhD",
        "name": "len: 10",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "UbKS62tIsvhM": {
        "type": 2,
        "id": "UbKS62tIsvhM",
        "name": "len: 8",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "PdYSwdaKczPD": {
        "type": 2,
        "id": "PdYSwdaKczPD",
        "name": "len: 15",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "s0-kYm-cXVaK": {
        "type": 2,
        "id": "s0-kYm-cXVaK",
        "name": "len: 5",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "0BJcTueRXGUR": {
        "type": 2,
        "id": "0BJcTueRXGUR",
        "name": "len: 8",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "pmsA015tCUeD": {
        "type": 2,
        "id": "pmsA015tCUeD",
        "name": "len: 6",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "ahi5ZhcEpF2H": {
        "type": 2,
        "id": "ahi5ZhcEpF2H",
        "name": "len: 10",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      },
      "ixO3f04oU8eL": {
        "type": 2,
        "id": "ixO3f04oU8eL",
        "name": "len: 9",
        "color": "blue",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveRules": [
          {
            "id": "kJsyxbRz1cfL",
            "active": true,
            "url": "about:",
            "name": "about:"
          }
        ],
        "moveExcludedTo": -1,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "srcPanelConfig": null
      }
    }
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "sidebarCSSLen": "1826",
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 309
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 1
    }
  ],
  "bookmarks": {
    "bookmarksCount": 0,
    "foldersCount": 4,
    "separatorsCount": 0,
    "maxDepth": 1
  }
}
```
</details>

<details>
<summary><b>Logs</b></summary>
Nil
</details>

**Comment by mbnuqw** [comment] 2024-03-30 12:56
It's expected behavior. Duplicate of #659

**Closed as completed by mbnuqw** 2024-03-30 12:56 UTC
Labels: type: duplicate
