### ISSUE TITLE
Tabs disappear when "Confirm leave" prompted by the website upon closing tab

### ISSUE THREAD

**Issue by nulledone** [mbnuqw/sidebery#1330] opened 2023-10-23 19:24 UTC
Latest Firefox.
Title, they re-appear when you refresh the sideberry by double tapping F1
![Untitled](https://github.com/mbnuqw/sidebery/assets/29547468/74c24926-2c47-4c51-92e5-dbe499de6825)

**Comment by ArtofBugs** [comment] 2023-11-06 20:58
Possible duplicate of https://github.com/mbnuqw/sidebery/issues/1246?

**Comment by mbnuqw** [comment] 2024-01-22 17:39
Duplicate of #1246

**Closed as completed by mbnuqw** 2024-01-22 17:39 UTC
Labels: type: duplicate
