### ISSUE TITLE
Settings page not showing settings

### ISSUE THREAD

**Issue by kamizoli** [mbnuqw/sidebery#219] opened 2020-05-06 08:29 UTC
## Steps to reproduce
1. Newly installed Sideberry, open settings, change settings, no indication of chosen setting.
![sidebar](https://user-images.githubusercontent.com/25310402/81154436-307a5500-8f84-11ea-9422-52e9e50865d1.jpg)

2. Click settings page > Panels > Default the sub menu opens overlaying the settings page, but page underneath is showing to strongly so sub menu is not readable very good.

![default menu](https://user-images.githubusercontent.com/25310402/81153558-52bfa300-8f83-11ea-9098-bb8c6b7f0148.jpg)

Or opening debug information will overlay them, but settings page is still showing strongly underneath and confusing the appearence.

![debug info](https://user-images.githubusercontent.com/25310402/81153563-53583980-8f83-11ea-9d10-0a314b39941f.jpg)

## Expected behavior
1. changing settings the on/off indicator should change
2. sub menu would cover underlying settings to be better readable

## Actual behavior
no change visible when altering settings

## Environment info

OS:  Windows 10
Firefox version:  76
Addon version:  4.8.0

<details><code>

</code>{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "21.7 kb",
    "props": {
      "containers_v4": "3.3 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "1.9 kb",
      "favicons": "8.3 kb",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "1.2 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "tabsData_v4": "3.7 kb"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 29
    }
  ],
  "bookmarks": {
    "bookmarksCount": 46,
    "foldersCount": 21,
    "separatorsCount": 0,
    "maxDepth": 4
  }
}</details>

**Comment by kamizoli** [comment] 2020-05-06 09:01
After changing the style from light to dark and back to light the settings are now indicating their state by with red or green. Also the overlay windows are now covering the site underneath.

**Comment by mbnuqw** [comment] 2020-05-06 17:44
Thanks for the report. I cannot reproduce this, so I can only guess what is the actual cause of this. It looks like Sidebery cannot set style (dark/light/auto) for the active theme. Hm...
Do you have userContent.css styles?

**Comment by kamizoli** [comment] 2020-05-06 21:34
Thank you for your quick response! I have no userContent.css styles or any theme installed. Plain Firerfox with some extensions. I don't know if they could be responsible. But I had the same problem on three profiles, with only some of the same extensions installed on all of the profiles.

**Comment by mbnuqw** [comment] 2020-05-10 19:09
I think, I found the cause of this! Will be fixed in the next version.

**Comment by kamizoli** [comment] 2020-05-10 19:35
Thats good! Thank you!

**Comment by mbnuqw** [comment] 2020-06-04 12:08
@kamizoli, could you check if v4.9.0 fix this?

**Comment by kamizoli** [comment] 2020-06-19 11:32
I took me a while to get to it. But I checked it now. The settings are working now out of the box. I tested with a new profil. One thing I noticed, Sidebery starts with a dark theme, the setting ist switched to auto. My Firefox uses the default light theme. I this due to the Mozilla addon site, which is dark as well? I have to switch Sidebery to light, that it will respect my preset.

**Comment by mbnuqw** [comment] 2024-03-31 15:28
Closing this as probably fixed.

**Closed by mbnuqw** 2024-03-31 15:28 UTC
Labels: type: bug
