### ISSUE TITLE
New link wrong container.

### ISSUE THREAD

**Issue by ameeno** [mbnuqw/sidebery#563] opened 2022-02-03 18:27 UTC
## Steps to reproduce
click on a link from anywhere. It stays in its current container and needs to be refreshed to use

## Expected behavior

I have been using containerise and multi account containers previously With that setup my sites always would open in the correct container.

but your extension does not do this.
## Actual behavior
opens websites in wrong containers.
 and needs to be refreshed to work. which is not good.

## Environment info
Mac M1 firefox 96.03

OS:  
Firefox version:  
Addon version:  

<details><code>

</code></details>

**Comment by SandNerd** [comment] 2022-04-10 20:23
Just wanted to chime in as I also use the containerise extension and have even built [a list](https://gist.github.com/SandNerd/cdf99747990bfbf3c4c125dc5b6c7fa3) for it that containerizes many popular sites by company. 

I was actually about to create separate issue for having an easy interface, like containerise, where we can add multiple new sites and containers Sidebery since now it could only be done with export/import JSON. However, reading issue above and seeing the whooping 339 open issues, I think I'll check back on this whenever is the next time that I look for new extensions, if ever. Peace.

**Comment by mbnuqw** [comment] 2023-02-11 19:37
Duplicate of #305, planned to be fixed soon (beta32-33)

**Closed by mbnuqw** 2023-02-11 19:37 UTC
