### ISSUE TITLE
[Feature request] Option to not overlap icon/fold/number

### ISSUE THREAD

**Issue by Zeioth** [mbnuqw/sidebery#1378] opened 2023-12-03 08:47 UTC
## Description
This is how the plugin looks normally

![screenshot_2023-12-03_09-40-27_245516621](https://github.com/mbnuqw/sidebery/assets/3357792/caa426fd-2f0c-4983-bd9f-b4d3c5f1e80d)

I would like to have a option to have a separation between icon/fold/number similar to the one  you have in the plugin tree style tab.
![screenshot_2023-12-03_09-43-55_273355289](https://github.com/mbnuqw/sidebery/assets/3357792/8ef887ec-72ac-484b-9d34-975214f4a3ed)

## Advantages:
* No need to fade the icon. This makes easier lo localize tabs visually.
* Having the fold icon on the left makes more obvious when a group is folded/unfolded.
* Optionally having the count on the right, would be nice, but not a deal breaker.

**Comment by mbnuqw** [comment] 2024-03-29 12:40
Duplicate of #794

**Closed as completed by mbnuqw** 2024-03-29 12:40 UTC
Labels: type: duplicate
