### ISSUE TITLE
Problems in KDE Plasma Wayland.

### ISSUE THREAD

**Issue by guigirl42** [mbnuqw/sidebery#839] opened 2022-11-07 02:52 UTC
## Steps to reproduce
- I have experienced/verified the misbehaviour symptoms in all of:
   - FF **Nightly** [my heavily customised (wrt both Nightly itself, + my many Sidebery changes) daily _**default**_ browser & profile], 
   - FF **Nightly** [_virgin_ Nightly profile with Sidebery as the only active AddOn, & _no changes_ in its Styles Editor], 
   - FF **Beta** [my heavily customised (wrt both Beta itself, + my many Sidebery changes) profile], and ...
   - standard **vanilla FF** [my heavily customised (wrt both FF itself, + my many Sidebery changes) profile].
- Afaik atm, the misbehaviour symptom only arises when running the browser as a full-Wayland app, in a KDE Plasma Wayland desktop session [atm i cannot remember for certain, but i think this never happens in an X11 session]. Nightly automatically adjusts itself to full-Wayland mode when it detects a Wayland session [ie, no user intervention needed]. For Beta & vanilla FF though, one launches via `MOZ_ENABLE_WAYLAND=1` preface. 
- My OS is ArchLinux, my Desktop Environment is KDE Plasma, & this problem has manifested across at least several Plasma versions [my current = 5.26.2].
- Sometimes i can go all day or longer without any sign of the problem, but other days the problem can commence within minutes. Until beginning to write this Issue, i had been unable to pinpoint a repeatable trigger, but now i know _at least_ one [there might be others; idk]: 
   - with multiple tabs open, manually rearrange some tabs by dragging & dropping with the mouse pointer. 
   - "disturb" the FF window graphically, eg, minimising it, or changing to a different virtual desktop.
   - return to the FF window, eg by restoring it, or returning to that virtual desktop.
   - at this point, reliably, the problem has initiated, both visually & functionally.
- The visual signs of the problem are:
   - an ugly horizontal line appears "permanently" in the tab panel.
   - said line begins at its LHS end with some kind of "arrowhead within arrowhead" artefact.
   - hovering the pointer over any tab's "cross" icon to close it, no longer changes the pointer icon from arrow to hand-with-extended-index-finger [which is what happens in X11, but also in Wayland prior to this problem triggering].
   - similarly, when there are any collapsed tab groups, hovering the pointer over said group's LHS "expand" icon, no longer changes the pointer icon from arrow to hand-with-extended-index-finger.
 - The functional consequences of the problem are:
   - tabs cannot be closed by LMB-clicking the hover-cross icon.
   - collapsed groups cannot be expanded by LMB-clicking the expand icon.
   - expanded groups cannot be collapsed by LMB-clicking the collapse icon, because it no longer exists within the group's folder icon.

## Expected behaviour
Sidebery should function 100% identically in Plasma Wayland sessions as it does in Plasma X11 sessions.

## Actual behaviour
- Until the bug triggers, it works the same in W as X.
- Once the bug triggers, important visual & functional deficiencies manifest, as described above. 
   - At this point, the user has limited options, each of which is poor:
      - Never drag & drop tabs to rearrange them.
      - Keep closing & restarting the browser.
      - Keep disabling then re-enabling Sidebery.
      - Keep toggling between Sidebery, Bookmarks, History, other sidebar-occupying AOs, in the FF Sidebar.
      - Disable Sidebery, revert to TreeStyleTab AO [unfortunately, this is what i have had to do] 😭
 - I might be completely wrong, but tbh i doubt this problem can be fixed by the Dev, because i strongly suspect the root cause lies not within Sidebery at all, but instead either with Firefox's implementation of running the browser in a Plasma Wayland session, &/or some bug in Plasma Wayland itself. However, i felt it was important to at least point out this problem to the Dev... 🤷‍♀️
- Pictures:
- ![2022-11-05_19 00 46](https://user-images.githubusercontent.com/76090786/200214805-788d92fa-dd2d-4026-b7a5-a3738560383c.png)    ![2022-11-07_11 05 18](https://user-images.githubusercontent.com/76090786/200214807-d68df1ba-3521-4bb5-8220-e172a5fa8783.png)

## Debug info

The following is from my "FF **Nightly** [_virgin_ Nightly profile with Sidebery as the only active AddOn, & _no changes_ in its Styles Editor]":

<details><summary><b>Addon data</b></summary><code>

</code>{
  "addonVersion": "5.0.0b28",
  "firefoxVersion": "108.0a1",
  "settings": {
    "nativeScrollbars": false,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": false,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "xxs",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "compact",
    "colorScheme": "ff",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "clipboardWrite": false,
    "webRequest": false,
    "webRequestBlocking": false
  },
  "storage": {
    "size": "112 kb",
    "props": {
      "containers": "3.15 kb",
      "contextMenu": "1.45 kb",
      "expandedBookmarkFolders": "75 b",
      "favDomains": "10.5 kb",
      "favHashes": "1.13 kb",
      "favicons": "75.5 kb",
      "groupCSS": "2 b",
      "lastSnapTime": "13 b",
      "prevTabsDataCache": "4.22 kb",
      "profileID": "14 b",
      "settings": "3.61 kb",
      "sidebar": "880 b",
      "sidebarCSS": "2 b",
      "snapshots": "5.51 kb",
      "tabsDataCache": "5.55 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "firefox-default": {
        "type": 2,
        "id": "firefox-default",
        "name": "len: 14",
        "color": "purple",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": true,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "bookmarks": {
        "type": 1,
        "id": "bookmarks",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "green",
        "lockedPanel": false,
        "tempMode": false,
        "skipOnSwitching": false,
        "rootId": "root________",
        "viewMode": "tree",
        "autoConvert": false
      },
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      }
    },
    "nav": [
      "firefox-default",
      "bookmarks",
      "history",
      "sp-0",
      "search",
      "settings"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "cookieStoreId": "firefox-container-6",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-7",
      "cookieStoreId": "firefox-container-7",
      "name": "25",
      "icon": "...",
      "color": "yellow",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-8",
      "cookieStoreId": "firefox-container-8",
      "name": "10",
      "icon": "...",
      "color": "red",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-9",
      "cookieStoreId": "firefox-container-9",
      "name": "9",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-10",
      "cookieStoreId": "firefox-container-10",
      "name": "7",
      "icon": "...",
      "color": "turquoise",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-11",
      "cookieStoreId": "firefox-container-11",
      "name": "4",
      "icon": "...",
      "color": "toolbar",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 55
    }
  ],
  "bookmarks": {
    "bookmarksCount": 8988,
    "foldersCount": 1209,
    "separatorsCount": 9,
    "maxDepth": 12
  }
}</details>

<details><summary><b>Logs</b></summary><code>

</code></details>
- NO entries appeared in Console.

**Comment by albino1** [comment] 2022-11-07 03:36
Probably related:

https://github.com/mbnuqw/sidebery/issues/809

**Comment by guigirl42** [comment] 2022-11-07 03:43
Oh wow, yes indeed, it seems the same. Well spotted, & thanks for pointing this out to me. 

Dare i hope, after all?

**Comment by mbnuqw** [comment] 2022-11-09 17:12
Duplicate of #809

**Closed as completed by mbnuqw** 2022-11-09 17:12 UTC
