### ISSUE TITLE
Panel bound to container - option to also auto-include Command+T tabs?

### ISSUE THREAD

**Issue by Glokta0** [mbnuqw/sidebery#492] opened 2021-10-07 14:24 UTC
## Description
My "Personal" panel has all container settings set to my personal container. Thus, if I add a new tab via Sideberry (i.e. double click on empty space), it ends up in that container.
If I open a new tab via the standard shortcut while being in this panel, it lands in no container. I don't know if you have access to these events/newly created tabs that were not created through Sideberry. Sideberrys internal keybindings work fine - but I'm running out of shortcuts, because of other scripts I use.
Thus, I wondered if there's a possibility to get to these newly firefox-created tabs to also follow the panels settings 🤔

Best

**Comment by mbnuqw** [comment] 2024-03-18 11:38
Duplicate of #305 ([workaround](https://github.com/mbnuqw/sidebery/issues/305#issuecomment-1740810382))

**Closed by mbnuqw** 2024-03-18 11:38 UTC
