### ISSUE TITLE
[v5.x.x]After closing the last tab, a new blank tab is not created automatically

### ISSUE THREAD

**Issue by dream-hack** [mbnuqw/sidebery#1230] opened 2023-09-15 12:23 UTC
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery [v5.0.0rc5](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0rc5)
- Close the last tab

## Expected behavior
automatic create a new blank tab after closing the last tab

## Actual behavior
After closing the last tab, a new blank tab is not created automatically, need to click the extension icon 2 times to display the blank tab.

v5.x :After closing the last tab, a new blank tab **is not** created automatically
![v5](https://github.com/mbnuqw/sidebery/assets/18359166/62dacdff-df8a-4e25-9277-6891e7a99c3d)

v4.x:After closing the last tab, a new blank tab **is** created automatically
![v4](https://github.com/mbnuqw/sidebery/assets/18359166/02cc7b1b-5894-441a-ac6e-8d846b47a6f0)

## Debug info

<details>
<summary><b>Addon data</b></summary>
     
```
{
  "addonVersion": "5.0.0rc5",
  "firefoxVersion": "117.0.1",
  "settings": {
    "nativeScrollbars": false,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": false,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "hideDiscardedTabPanels": false,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navTabsPanelMidClickAction": "discard",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "subPanelRecentlyClosedBar": false,
    "subPanelBookmarks": false,
    "subPanelHistory": false,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": false,
    "dndTabActDelay": 1000,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 1000,
    "dndExpMod": "none",
    "dndOutside": "data",
    "dndActTabFromLink": true,
    "dndActSearchTab": true,
    "dndMoveTabs": false,
    "dndMoveBookmarks": false,
    "searchBarMode": "dynamic",
    "searchPanelSwitch": "same_type",
    "searchBookmarksShortcut": "",
    "searchHistoryShortcut": "",
    "warnOnMultiTabClose": "any",
    "activateLastTabOnPanelSwitching": true,
    "activateLastTabOnPanelSwitchingLoadedOnly": true,
    "switchPanelAfterSwitchingTab": "always",
    "tabRmBtn": "hover",
    "activateAfterClosing": "next",
    "activateAfterClosingStayInPanel": false,
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "tabsUnreadMark": true,
    "tabsUpdateMark": "all",
    "tabsUpdateMarkFirst": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": false,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": true,
    "tabsPanelSwitchActMoveAuto": true,
    "tabsUrlInTooltip": "full",
    "newTabCtxReopen": false,
    "tabWarmupOnHover": true,
    "tabSwitchDelay": 0,
    "moveNewTabPin": "start",
    "moveNewTabParent": "default",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "pinnedAutoGroup": false,
    "pinnedNoUnload": false,
    "tabsTree": true,
    "groupOnOpen": false,
    "tabsTreeLimit": "none",
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "autoExpandTabsOnNew": false,
    "rmChildTabs": "none",
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "ignoreFoldedParent": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "colorizeTabsBranches": true,
    "colorizeTabsBranchesSrc": "domain",
    "inheritCustomColor": true,
    "hideInact": false,
    "hideFoldedTabs": false,
    "hideFoldedParent": "none",
    "nativeHighlight": false,
    "warnOnMultiBookmarkDelete": "any",
    "autoCloseBookmarks": true,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": false,
    "oldBookmarksAfterSave": "ask",
    "loadHistoryOnDemand": true,
    "fontSize": "xxs",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "proton",
    "density": "compact",
    "colorScheme": "ff",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "snapAutoExport": false,
    "snapAutoExportType": "json",
    "snapAutoExportPath": "Sidebery/snapshot-%Y.%M.%D-%h.%m.%s",
    "snapMdFullTree": false,
    "hScrollAction": "switch_act_tabs",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "reload",
    "tabsSecondClickActPrev": false,
    "tabsSecondClickActPrevPanelOnly": false,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabMiddleClick": "close",
    "tabMiddleClickCtrl": "discard",
    "tabMiddleClickShift": "duplicate",
    "tabCloseMiddleClick": "discard",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "undo",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": true,
    "bookmarksMidClickRemove": false,
    "bookmarksMidClickPos": "default",
    "historyLeftClickAction": "open_in_act",
    "historyLeftClickActivate": false,
    "historyLeftClickPos": "default",
    "historyMidClickAction": "open_in_new",
    "historyMidClickActivate": false,
    "historyMidClickPos": "default",
    "syncName": "firefox@e430c",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncSaveKeybindings": true,
    "selectActiveTabFirst": true
  },
  "permissions": {
    "allUrls": false,
    "webRequest": false,
    "webRequestBlocking": false,
    "proxy": false,
    "tabHide": false,
    "clipboardWrite": false,
    "history": false,
    "bookmarks": true,
    "downloads": false
  },
  "storage": {
    "size": "639 kb",
    "props": {
      "containers": "1.07 kb",
      "contextMenu": "1.33 kb",
      "favDomains": "42.5 kb",
      "favHashes": "7.95 kb",
      "favicons_01": "578 kb",
      "profileID": "14 b",
      "settings": "4.8 kb",
      "sidebar": "914 b",
      "sidebarCSS": "588 b",
      "tabsDataCache": "831 b",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "nav": [
      "ynSEqlEezLwj",
      "Tsj4UyQPbJwj",
      "history",
      "search",
      "add_tp",
      "settings"
    ],
    "panels": {
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": true,
        "lockedPanel": true,
        "skipOnSwitching": false,
        "viewMode": "history"
      },
      "ynSEqlEezLwj": {
        "type": 2,
        "id": "ynSEqlEezLwj",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "bookmarksFolderId": -1,
        "newTabBtns": [],
        "moveRules": [],
        "moveExcludedTo": -1,
        "srcPanelConfig": null
      },
      "Tsj4UyQPbJwj": {
        "type": 1,
        "id": "Tsj4UyQPbJwj",
        "name": "len: 9",
        "iconSVG": "icon_bookmarks",
        "iconIMGSrc": "",
        "iconIMG": "",
        "color": "toolbar",
        "lockedPanel": true,
        "tempMode": true,
        "skipOnSwitching": false,
        "rootId": "toolbar_____",
        "viewMode": "tree",
        "autoConvert": false,
        "srcPanelConfig": null
      }
    }
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "8",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "4",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "7",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "reopenRulesActive": false,
      "reopenRules": [],
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "sidebarCSSLen": "570",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 4
    }
  ],
  "bookmarks": {
    "bookmarksCount": 210,
    "foldersCount": 16,
    "separatorsCount": 0,
    "maxDepth": 3
  }
}
```
</details>

<details>
<summary><b>Logs</b></summary>

```
[sidebar] Init start chunk-32W5D3LQ.js:2:7807
[bg] Init start chunk-32W5D3LQ.js:2:7807
[sidebar:1] Sidebar.loadPanels chunk-32W5D3LQ.js:2:7807
[sidebar:1] Sidebar.loadPanels: Done: 25ms chunk-32W5D3LQ.js:2:7807
[sidebar:1] Tabs.load chunk-32W5D3LQ.js:2:7807
[sidebar:1] Tabs.restoreTabsState chunk-32W5D3LQ.js:2:7807
[bg] Windows.isWindowTabsLocked 1 chunk-32W5D3LQ.js:2:7807
[bg] IPC.onConnected sidebar 1 chunk-32W5D3LQ.js:2:7807
[bg] Init end: 406ms chunk-32W5D3LQ.js:2:7807
[sidebar:1] Tabs.findCachedData: mismatched: 1 1 1 chunk-32W5D3LQ.js:2:7893
[sidebar:1] Tabs.restoreTabsFromSessionData chunk-32W5D3LQ.js:2:7807
[sidebar:1] Tabs loading: Cannot find panels: -1 chunk-32W5D3LQ.js:2:7893
[sidebar:1] Tabs.restoreTabsState: Done: 126ms chunk-32W5D3LQ.js:2:7807
[sidebar:1] Tabs.load: Done: 145ms chunk-32W5D3LQ.js:2:7807
[sidebar:1] Init end: 590ms chunk-32W5D3LQ.js:2:7807

```
</details>

**Comment by mbnuqw** [comment] 2023-09-17 15:37
Open sidebery settings >> Navigation bar >> Panel config and enable "Create new tab after the last one is closed"

**Comment by mbnuqw** [comment] 2023-09-17 16:16
Oh, got it. You're using the `browser.tabs.closeWindowWithLastTab: false`, which indeed causing this behavior.

**Comment by martinlbrook** [comment] 2023-09-30 18:31
I also have this bug - enabling "Create new tab after the last one is closed" does indeed work but only when the tab is closed by clicking the close button in the sidebar. If a tab is closed with Ctrl/Cmd W, the issue still happens.

**Comment by viktor-yunenko** [comment] 2023-11-06 00:44
One workaround is to intercept the Firefox's native `Close Tab` shortcut and trigger Sidebery's native `Close selected or active tab` shortcut, for example on MacOS:
- Turn on in Sidebery Settings: `Configure panel` -> `Create a new tab after the last one is closed`
  <details><summary>Screenshot</summary>
  <p><img width="1143" alt="image" src="https://github.com/mbnuqw/sidebery/assets/36416236/2fb20363-1fe9-4190-b6bd-114a9259dc7b"></p></details>
- In Sidebery Keybinding set a keyboard shortcut to something rare on `Close selected or active tab / Delete selected bookmarks`
  - in my case I used `Ctrl + Cmd + 0` (Sidebery displays `Cmd` as `Ctrl` on macos for some reason)
  <details><summary>Screenshot</summary><p><img width="1204" alt="image" src="https://github.com/mbnuqw/sidebery/assets/36416236/5e3dff09-31bd-471c-8559-4b41cae2cda5"></p></details> 
- In a tool like BetterTouchTool or Keyboard Maestro for Firefox create a trigger that intercepts the native `Cmd + W` shortcut and instead triggers your Sidebery shortcut for `Close selected or active tab / Delete selected bookmarks`
  - in my case, again, `Ctrl + Cmd + 0`
  <details><summary>Screenshot of BTT</summary><p><img width="1143" alt="image" src="https://github.com/mbnuqw/sidebery/assets/36416236/b841c18d-a32d-409f-a806-1c8f5434168a"></p></details> 

Thank you @martinlbrook for figuring out the problem trigger!

**Comment by alurm** [comment] 2024-01-16 22:03
To state the obvious, another workaround is to always leave a tab open. For example, some tab can be pinned, since pinned tabs are not as easy to close as regular tabs are.

**Comment by iripu** [comment] 2024-03-13 12:26
I have tried other sidebar tabs extensions and none of them has this problem, only sidebery.

**Comment by kabuda2077** [comment] 2024-03-30 17:47
> One workaround is to intercept the Firefox's native `Close Tab` shortcut and trigger Sidebery's native `Close selected or active tab` shortcut, for example on MacOS:
> 
>     * Turn on in Sidebery Settings: `Configure panel` -> `Create a new tab after the last one is closed`
>       Screenshot
>       <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/36416236/280565904-2fb20363-1fe9-4190-b6bd-114a9259dc7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjA5OTYsIm5iZiI6MTcxMTgyMDY5NiwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjU5MDQtMmZiMjAzNjMtMWZlOS00MTkwLWI2YmQtMTE0YTkyNTlkYzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE3NDQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OTEzZTI3NmRmMmQ5OTZmZTVhZjI3NjRmNzlmNTEzNDc3MzAwNDI3NWY3NWYzN2EyYzhiMTY0MDMzYTk1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ril8XCpmqLpINcHfyxdhUC1dKzmnuElCYzugGk7bs1E">
> 
>     * In Sidebery Keybinding set a keyboard shortcut to something rare on `Close selected or active tab / Delete selected bookmarks`
>       
>       * in my case I used `Ctrl + Cmd + 0` (Sidebery displays `Cmd` as `Ctrl` on macos for some reason)
>       
>       Screenshot<img alt="image" width="1204" src="https://private-user-images.githubusercontent.com/36416236/280565229-5e3dff09-31bd-471c-8559-4b41cae2cda5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjA5OTYsIm5iZiI6MTcxMTgyMDY5NiwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjUyMjktNWUzZGZmMDktMzFiZC00NzFjLTg1NTktNGI0MWNhZTJjZGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE3NDQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyN2IyYWE2MjBlNjY1ZmM0NmMzMGIxNWRmOTdiMjg5ODA3OTNhZjAxNzM1OGI2YTkxMmEwY2ZlOTJmNzNlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9dB51nsZWR3NIttEijNMlo9Kqnay4hp-z0GC_WvDIg">
> 
>     * In a tool like BetterTouchTool or Keyboard Maestro for Firefox create a trigger that intercepts the native `Cmd + W` shortcut and instead triggers your Sidebery shortcut for `Close selected or active tab / Delete selected bookmarks`
>       
>       * in my case, again, `Ctrl + Cmd + 0`
>       
>       Screenshot of BTT<img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/36416236/280565723-b841c18d-a32d-409f-a806-1c8f5434168a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjA5OTYsIm5iZiI6MTcxMTgyMDY5NiwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjU3MjMtYjg0MWMxOGQtYTMyZC00MDlmLWE4MDYtMWM4ZjU0MzQxNjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE3NDQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5Zjg3NWQ3ZmJkMjI2M2YyYmJiZWI0MWUyMzA2ZDAxMWI5MmYyNzFhZjdiMTU0YWM2OGY4ZDdjZTU4YThjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRgUEHmeS9UqxE7WcSCbw_14k0S1xoqf33yl3xNDBqY">
> 
> 
> Thank you @martinlbrook for figuring out the problem trigger!

could you please tell me how to open configure panel, I can't find this page

**Comment by kabuda2077** [comment] 2024-03-31 05:40
> 一种解决方法是拦截 Firefox 的本机 `Close Tab`快捷方式并触发 Sidebery 的原生 `Close selected or active tab`快捷方式，例如在 MacOS 上：
> 
>     * 在 Sidebery 设置中打开： `Configure panel`-> `Create a new tab after the last one is closed`
>       截屏 
>       <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/36416236/280565904-2fb20363-1fe9-4190-b6bd-114a9259dc7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjMwMzgsIm5iZiI6MTcxMTg2MjczOCwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjU5MDQtMmZiMjAzNjMtMWZlOS00MTkwLWI2YmQtMTE0YTkyNTlkYzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA1MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNjQzZjlhZjk5ZGUzODQ0MWJmNzUzYmQ4ODAxOWI3MTYwZjY5NGIwMGEyMDViODMwMjc1MTllOGIyNmU2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thwUtPEOQBmatbZFHwC9EPcWGeTIen7zqp-iZAnwi9I">
> 
>     * 在 Sidebery 键绑定中，将键盘快捷键设置为罕见的内容 `Close selected or active tab / Delete selected bookmarks`
>       
>       * 就我而言，我用过 `Ctrl + Cmd + 0`（侧边栏显示 `Cmd`作为 `Ctrl`由于某种原因在 Macos 上）
>       
>       截屏 <img alt="image" width="1204" src="https://private-user-images.githubusercontent.com/36416236/280565229-5e3dff09-31bd-471c-8559-4b41cae2cda5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjMwMzgsIm5iZiI6MTcxMTg2MjczOCwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjUyMjktNWUzZGZmMDktMzFiZC00NzFjLTg1NTktNGI0MWNhZTJjZGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA1MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzVlNTE5OGRmMDJmNjZjMDM4MDBlZTUzMDQ0NTg1MWI3Y2ZiOTgxODYyZTVkM2UxNzA3NzVmNTZjMWM5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QGLw8Xz4a4gaA9qlbavm9KW0LqdN2lmvyncnaklgsJ0">
> 
>     * 在 BetterTouchTool 或 Keyboard Maestro for Firefox 等工具中，创建一个拦截本机的触发器 `Cmd + W`快捷方式，而是触发您的 Sidebery 快捷方式 `Close selected or active tab / Delete selected bookmarks`
>       
>       * 就我而言，再次， `Ctrl + Cmd + 0`
>       
>       BTT截图 <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/36416236/280565723-b841c18d-a32d-409f-a806-1c8f5434168a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjMwMzgsIm5iZiI6MTcxMTg2MjczOCwicGF0aCI6Ii8zNjQxNjIzNi8yODA1NjU3MjMtYjg0MWMxOGQtYTMyZC00MDlmLWE4MDYtMWM4ZjU0MzQxNjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA1MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMmQ5ZDc4NTgwYjZlMWZlMWQ0OTg3YTZmMGRhNjg4YjlmNTE4OGUxODA0MDNlZTZiOWRmMzlhODkzZjUwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYY1zXZVWocV70E7yA3VddfvrRuXj7HED9f3BdRyuXc">
> 
> 
> 谢谢 @martinlbrook找出问题触发点！

I can't find "Create a new tab after the last one is closed". Is it because the version has been updated or because macos and windows are different?

**Comment by ahahahaah** [comment] 2024-04-04 12:31
> Open sidebery settings >> Navigation bar >> Panel config and enable "Create new tab after the last one is closed"

i don't have "panel config" nor "create new tab after the last one is closed".

**Comment by kabuda2077** [comment] 2024-04-04 12:44
> > 打开sidebery设置>>导航栏>>面板配置并启用“关闭最后一个选项卡后创建新选项卡”
> 
> 我没有“面板配置”，也没有“最后一个选项卡关闭后创建新选项卡”。

Right-click the navigation bar icon, the third from the bottom is the configuration panel

**Comment by ahahahaah** [comment] 2024-04-04 13:59
> > > 打开sidebery设置>>导航栏>>面板配置并启用“关闭最后一个选项卡后创建新选项卡”
> > 
> > 
> > 我没有“面板配置”，也没有“最后一个选项卡关闭后创建新选项卡”。
> 
> Right-click the navigation bar icon, the third from the bottom is the configuration panel

thank you sir

**Closed as completed** 2024-04-06 15:35 UTC
Labels: type: bug, reproduced: yes

**Comment by ahahahaah** [comment] 2024-04-07 11:24
even with the "create new tab after the last one is closed" option activated the problem still occurs if we close the last firefox opened tab (tabs that are horizontal in the firefox tab bar).

**Comment by ZaWertun** [comment] 2024-06-06 11:03
Is it fixed?
I can reproduce this issue with Sidebery 5.2.0 and Firefox 126.0.

**Comment by martinlbrook** [comment] 2024-06-06 13:15
Not yet in the stable version, but I've downloaded the nightly release ([5.2.0.8](https://github.com/mbnuqw/sidebery/releases/download/v5.2.0/sidebery-5.2.0.8.xpi)) and can confirm that it's fixed.

**Comment by CamRatliff** [comment] 2025-01-07 17:22
In, both, Arch Linux and MacOS, on Sidebery 5.2.0 in Firefox 133.0.3, I'm still experiencing this behavior when closing tabs out via ctrl+w, firefox's native tabbar, and the "List All Tabs" toolbar button. Has this issue returned?

**Comment by doxxx** [comment] 2025-01-18 21:28
On CachyOS (Arch-based), using Cachy browser (Firefox 134) and Sideberry 5.2.0, with `browser.tabs.closeWindowWithLastTab` set to `false`, closing the last tab breaks Sideberry. Sideberry doesn't show the New Tab that is created when the last tab is closed. Creating more New Tabs does not show them in Sideberry. Hiding and showing Sideberry fixes the issue.

**Comment by ButterSus** [comment] 2025-08-03 14:09
on NixOs:
```
"addonVersion": "5.2.0",
"firefoxVersion": "139.0.4"
```
Can reproduce this issue. Same what @doxxx mentioned above
