### ISSUE TITLE
Pop-Up Windows Have 1st tab as a Group from another window

### ISSUE THREAD

**Issue by megamorphg** [mbnuqw/sidebery#618] opened 2022-05-01 18:31 UTC
## Steps to reproduce
1. Have a tab group setup in one window
2. Open another window
3. Go to a page with pop-up windows (like SSO on Groupon)
4. Try to trigger the pop-up window

## Expected behavior
Pop-up window appears without any group

## Actual behavior
Pop-up window has a group as the 1st tab
After opening pop-up:
![image](https://user-images.githubusercontent.com/1782353/166159518-72ac4c2d-a1e4-44ca-a808-1f7102e11272.png)
After closing the active tab in pop-up:
![image](https://user-images.githubusercontent.com/1782353/166159521-26e300b5-2a26-4dfd-8325-95ee68c4cc55.png)

### Addon data
<details><code>{
  "settings": {
    "version": "4.10.1",
    "nativeScrollbars": true,
    "selWinScreenshots": false,
    "tabsCheck": true,
    "tabsFix": "reinit",
    "markWindow": false,
    "markWindowPreface": "[SB] ",
    "ctxMenuNative": true,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": false,
    "navActTabsPanelLeftClickAction": "new_tab",
    "navActBookmarksPanelLeftClickAction": "scroll",
    "navMidClickAction": "rm_all",
    "navSwitchPanelsWheel": true,
    "groupLayout": "list",
    "skipEmptyPanels": true,
    "dndTabAct": true,
    "dndTabActDelay": 1500,
    "dndTabActMod": "alt",
    "dndExp": "pointer",
    "dndExpDelay": 50,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "none",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": true,
    "activateAfterClosing": "prev",
    "activateAfterClosingPrevRule": "any",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": true,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": true,
    "tabsRmUndoNote": true,
    "nativeHighlight": true,
    "tabsUnreadMark": true,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "tabsPanelSwitchActMove": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "first_child",
    "moveNewTabParentActPanel": true,
    "moveNewTab": "none",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": true,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": true,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": 3,
    "autoExpandTabs": false,
    "rmChildTabs": "folded",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": true,
    "discardFoldedDelay": 10,
    "discardFoldedDelayUnit": "min",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "first_child",
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": true,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": true,
    "bookmarksRmUndoNote": true,
    "fontSize": "xl",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "tactile",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 3,
    "snapIntervalUnit": "hr",
    "snapLimit": 100,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": true,
    "scrollThroughTabs": "panel",
    "scrollThroughVisibleTabs": true,
    "scrollThroughTabsSkipDiscarded": true,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": true,
    "tabDoubleClick": "reload",
    "tabLongLeftClick": "duplicate",
    "tabLongRightClick": "new_child",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "collapse",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "rm_act_tab",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": true,
    "syncSaveStyles": true,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "4 mb",
    "props": {
      "bookmarksMenu": "226 b",
      "bookmarksPanelMenu": "54 b",
      "containers_v4": "1.2 kb",
      "cssVars": "110 b",
      "expandedBookmarks": "18 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "84.7 kb",
      "favicons": "3.6 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels_v4": "1.3 kb",
      "prevTabsData_v4": "110.8 kb",
      "profileID": "14 b",
      "settings": "2.8 kb",
      "snapshots_v4": "133.6 kb",
      "tabsData_v4": "107.8 kb",
      "tabsMenu": "395 b",
      "tabsPanelMenu": "184 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "oPvtGQIvR9Am",
      "name": 1,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "77PJQY1X7zAm",
      "name": 1,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    },
    {
      "type": "tabs",
      "id": "Gi2njE8Dnlan",
      "name": 1,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "name": 7,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "name": 3,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": {},
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 84
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 68
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 45
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 177
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 181
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 36
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 198
    }
  ],
  "tabsMenu": [
    "undoRmTab",
    "mute",
    "bookmark",
    "reload",
    "separator-1",
    [
      {
        "name": "Move to"
      },
      "moveToNewWin",
      "moveToWin",
      "moveToPanel"
    ],
    [
      {
        "name": "Reopen in"
      },
      "reopenInNewWin",
      "reopenInWin",
      "reopenInCtr"
    ],
    "separator-2",
    "pin",
    "duplicate",
    "discard",
    "copyUrls",
    "separator-3",
    "group",
    "flatten",
    "separator-4",
    "clearCookies",
    [
      {
        "name": "Close"
      },
      "close",
      "closeDescendants",
      "closeTabsAbove",
      "closeTabsBelow",
      "closeOtherTabs"
    ]
  ],
  "bookmarksMenu": [
    [
      {
        "name": "Open in"
      },
      "openInNewWin",
      "openInNewPrivWin",
      "openInCtr"
    ],
    "separator-5",
    "createBookmark",
    "createFolder",
    "createSeparator",
    "separator-6",
    "sortByName",
    "sortByLink",
    "sortByTime",
    "separator-7",
    "copyUrls",
    "edit",
    "delete"
  ],
  "bookmarks": {
    "bookmarksCount": 1744,
    "foldersCount": 228,
    "separatorsCount": 1,
    "maxDepth": 5
  }
}
</code></details>

### Logs
<details><code>
Storage access automatically granted for origin “https://accounts.google.com/” on “https://www.groupon.com/”.
TypeError: NetworkError when attempting to fetch resource. [optimize-suite-v2-531e5db9fd.js:2:85849](https://www2.grouponcdn.com/layout/assets/optimize-suite-v2-531e5db9fd.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://na.groupondata.com/tracky. (Reason: CORS request did not succeed). Status code: (null).

TypeError: NetworkError when attempting to fetch resource. optimize-suite-v2-531e5db9fd.js:2:85849
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://na.groupondata.com/tracky. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://na.groupondata.com/tracky. (Reason: CORS request did not succeed). Status code: (null).

TypeError: NetworkError when attempting to fetch resource. [optimize-suite-v2-531e5db9fd.js:2:85849](https://www2.grouponcdn.com/layout/assets/optimize-suite-v2-531e5db9fd.js)
</code></details>

**Comment by megamorphg** [comment] 2022-05-02 16:03
This is actually a more annoying bug than I originally thought.
Another test case triggers the same bug:
1. Open a Gmail PDF for print
![image](https://user-images.githubusercontent.com/1782353/166267019-86e3efc5-936d-48b8-8f62-b35d159fda89.png)
2. Observe a new window flashes and opens and then hides
![image](https://user-images.githubusercontent.com/1782353/166266822-e7873873-26f7-43d4-acf1-80d91217719c.png)
3. PDF also opens in a new sub-tab properly
![image](https://user-images.githubusercontent.com/1782353/166266953-cfcd2397-a35c-4084-bf3f-68030feb4bb8.png)

**Comment by mbnuqw** [comment] 2024-03-08 06:30
Closing, as I can't reproduce this issue in v5, feel free to reopen if it still exists.

**Closed by mbnuqw** 2024-03-08 06:30 UTC
Labels: type: bug, status: resolved in beta
