### ISSUE TITLE
Large session optimization

### ISSUE THREAD

**Issue by OmTatSat** [mbnuqw/sidebery#963] opened 2023-02-26 19:24 UTC
Please add the ability to unload tabs to bookmarks by deleting them from opened tabs(tab session), but continue to display them in the tab tree like before unload. And when clicked, load a real tab.

In this way, we can achive speeding up Firefox browsing with large amounts of structured in trees opened sites

**Comment by mbnuqw** [comment] 2024-03-24 08:21
Duplicate of #1018

**Closed as completed by mbnuqw** 2024-03-24 08:21 UTC
Labels: type: duplicate
