### ISSUE TITLE
Sideberry Not Restoring Tabs When Close With Private Window Running

### ISSUE THREAD

**Issue by Titas22** [mbnuqw/sidebery#1423] opened 2024-01-21 18:07 UTC
## Steps to reproduce
- Open a fresh Firefox session
- Open some random website
- Also open a Private Window (ctrl+shift+P)
- Close the normal window
- Start Firefox again

## Expected/Actual behavior
I would expect the normal session to retain the tab selection when restarting, however with a private session running on the side it seem to do not.
At first I thought this could be related to allowing Sidebery to run in the private window but the behaviour does not change even after disabling that in the extension settings.

**Comment by llc0930** [comment] 2024-01-26 06:14
If I remember correctly, you should get the same results if you do the same thing without using Sideberry. That's apparently a behavioral issue with Firefox, because you're only closing the normal window, so "open previous windows and tabs" doesn't work. If you close both of them using Firefox's exit feature, tabs in the normal window should be restored as you would expect. The private window should obviously not be restored, that is its design goal.

**Comment by mbnuqw** [comment] 2024-03-30 13:03
Sidebery is not intended to restore any tabs on initialization. It uses tabs restored by Firefox itself, so this is expected behavior.
Related feature requests: #59, #721.

**Closed as completed by mbnuqw** 2024-03-30 13:03 UTC
Labels: type: not a bug
