### ISSUE TITLE
Random permissions requests "Sidebery requests additional permissions"

### ISSUE THREAD

**Issue by vitonsky** [mbnuqw/sidebery#1519] opened 2024-03-12 19:41 UTC
Hi, sometimes firefox show a permissions requests of Sidebery

![image](https://github.com/mbnuqw/sidebery/assets/86191922/0799f515-eadf-4a3b-9ff2-6e881fedb11f)

I don't know what a trigger for this request, but i seen it recently, few minutes ago when i tried to close tab by middle mouse click on tab.

I like Sidebery, it feels a really powerful and i trust this addon, because it does not require unnecessary permissions, but when i see this permissions request it fears me and it looks suspicious. I feel this permissions request as threat for the trust to a great addon, so it would be wise to fix it, to not alienate a paranoid users

**Comment by mbnuqw** [comment] 2024-03-13 08:22
Looks like a bug. Sidebery asks for these permissions (if they're not granted yet) in the next cases:
- When you're configuring site for auto reopen in a container (sidebar / settings page)
- When you're configuring proxy for a container (settings page)
- When you're configuring UserAgent for a container (settings page)
- When you're fetching favicons for bookmarks (settings page)
- When you're toggling the "Show screenshots in..." option (settings page > general section)
- When you're toggling tab preview (settings page)
- When you're clearing tab's cookies from context menu (sidebar)
- When you're middle-clicking on the "audio" badge to pause/play media content of tab (sidebar)
- I guess that's it...

All these cases are triggered directly on a user action (you must click on some button, text-field, menu option), so I don't know (yet) how this popup can randomly appear.

You can try to open sidebery settings page > General > Permissions and toggle on and off the "Accessing web requests data".

Also, could you provide your debug info (Sidebery settings > Help > Show debug info > Copy)?

**Comment by vitonsky** [comment] 2024-03-13 10:00
It looks i just misclick by audio icon on tab, instead of click by tab. I just tried, it reproduces stable.

So probably it is not a bug. Thank you for behavior explanation

**Comment by mbnuqw** [comment] 2024-03-13 11:09
Alright, closing this as not a bug. I'll think how to make this permission request more obvious to the user or just optional...

**Closed as completed by mbnuqw** 2024-03-13 11:09 UTC
Labels: type: not a bug
